import { memo, useEffect, useRef, useState } from "react";
import { CHAT_SLASH_COMMANDS, type ContextUsage, type SlashCommandInfo, type ToolCall } from "@visual-reader/core";
import { ContextUsageDonut } from "./ContextUsageDonut.js";

/**
 * The reading-companion chat panel. Pure presentation: messages, a streaming
 * bubble, inline tool results (search links / images), and the approval bubble
 * for a pending generate_image call — all state lives in the App, which talks to
 * the engine worker. Memoised so token-rate updates re-render only this panel.
 */

export interface ChatMessageVM {
  role: "user" | "assistant" | "tool";
  text: string;
  /** Inline image: generated bytes, or a hotlinkable retrieved figure. */
  image?: { bytes: ArrayBuffer; mimeType: string } | { sourceUrl: string };
  /** Source links from a search tool. */
  links?: { url: string; title?: string }[];
  /** Clickable local-file results (desktop `/find`); each opens the book on click. */
  files?: { path: string; name: string }[];
}

export interface ChatPanelProps {
  title: string;
  messages: ChatMessageVM[];
  /** In-flight assistant text (streaming providers), shown as a live bubble. */
  streamingText?: string;
  busy: boolean;
  /** Transient activity line ("searching the web…"). */
  activity?: string;
  /** An un-executed generate_image awaiting the reader's approval. */
  pendingTool?: ToolCall;
  allowSpoilers: boolean;
  /** Technical books always see the whole text — hides the spoiler toggle. */
  technical: boolean;
  onSend: (text: string) => void;
  onApprovePendingTool: () => void;
  onDismissPendingTool: () => void;
  onToggleSpoilers: (v: boolean) => void;
  onCancel: () => void;
  onClose: () => void;
  onClearHistory: () => void;
  /** Delete one message by index (must be referentially stable — see MessageBubble). */
  onDeleteMessage?: (index: number) => void;
  /** Compact the conversation into a summary (frees the model's context window). */
  onCompact?: () => void;
  /** Latest context-usage breakdown (for the usage donut). */
  contextUsage?: ContextUsage;
}

export const ChatPanel = memo(function ChatPanel(props: ChatPanelProps) {
  const [draft, setDraft] = useState("");
  const scrollRef = useRef<HTMLDivElement>(null);
  // Follow the conversation: stick to the bottom as messages/tokens arrive.
  useEffect(() => {
    const el = scrollRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [props.messages.length, props.streamingText, props.pendingTool, props.activity]);

  const send = () => {
    const text = draft.trim();
    if (!text || props.busy) return;
    setDraft("");
    props.onSend(text);
  };

  return (
    <div style={overlayStyle}>
      <div style={panelStyle}>
        <div style={headerStyle}>
          <strong style={{ fontSize: 14 }}>Chat · {props.title}</strong>
          <span style={{ marginLeft: "auto", display: "flex", gap: 8, alignItems: "center" }}>
            {!props.technical && (
              <label style={{ display: "flex", gap: 4, alignItems: "center", fontSize: 11, opacity: 0.8 }}>
                <input
                  type="checkbox"
                  checked={props.allowSpoilers}
                  onChange={(e) => props.onToggleSpoilers(e.target.checked)}
                />
                allow spoilers (whole book)
              </label>
            )}
            {props.onCompact && props.messages.length > 4 && (
              <button
                style={smallButtonStyle}
                onClick={props.onCompact}
                disabled={props.busy}
                title="Summarize the conversation so far and continue from the summary (frees the model's memory)"
              >
                Compact
              </button>
            )}
            <button style={smallButtonStyle} onClick={props.onClearHistory} title="Clear this book's chat history">
              Clear
            </button>
            <button style={smallButtonStyle} onClick={props.onClose}>
              Close
            </button>
          </span>
        </div>

        {props.contextUsage && <UsageDisclosure usage={props.contextUsage} />}

        <div ref={scrollRef} style={scrollStyle}>
          {props.messages.length === 0 && !props.streamingText && (
            <div style={{ opacity: 0.55, fontSize: 12, padding: 12 }}>
              Ask about what you’re reading — characters, concepts, “find a diagram of…”,
              or “draw …, 20 steps, flux 2”.{" "}
              {props.technical
                ? "This technical book is fully visible to the chat."
                : "The chat only knows the book up to your current position (toggle spoilers above)."}
            </div>
          )}
          {props.messages.map((m, i) => (
            <MessageBubble key={i} message={m} index={i} {...(props.onDeleteMessage ? { onDelete: props.onDeleteMessage } : {})} />
          ))}
          {props.streamingText ? (
            <MessageBubble message={{ role: "assistant", text: props.streamingText }} />
          ) : null}
          {props.activity ? (
            <div style={{ opacity: 0.6, fontSize: 12, padding: "2px 8px" }}>{props.activity}</div>
          ) : null}
          {props.pendingTool?.tool === "generate_image" && (
            <div style={approvalStyle}>
              <div style={{ fontSize: 12, marginBottom: 6 }}>
                Generate this image?
                <span style={{ display: "block", opacity: 0.7, marginTop: 2 }}>
                  “{props.pendingTool.prompt}”
                  {props.pendingTool.model ? ` · model: ${props.pendingTool.model}` : ""}
                  {props.pendingTool.steps ? ` · ${props.pendingTool.steps} steps` : ""}
                  {props.pendingTool.style ? ` · style: ${props.pendingTool.style}` : ""}
                </span>
              </div>
              <button style={{ ...smallButtonStyle, marginRight: 6 }} onClick={props.onApprovePendingTool}>
                Run
              </button>
              <button style={smallButtonStyle} onClick={props.onDismissPendingTool}>
                Dismiss
              </button>
            </div>
          )}
        </div>

        <SlashMenu draft={draft} commands={CHAT_SLASH_COMMANDS} onPick={setDraft} />
        <div style={inputRowStyle}>
          <textarea
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                send();
              } else if (e.key === "Tab") {
                const completed = completeSlash(draft, CHAT_SLASH_COMMANDS);
                if (completed) {
                  e.preventDefault();
                  setDraft(completed);
                }
              }
            }}
            placeholder={props.busy ? "Thinking…" : "Ask about the book… (Enter to send, / for commands)"}
            rows={2}
            style={textareaStyle}
          />
          {props.busy ? (
            <button style={smallButtonStyle} onClick={props.onCancel}>
              Stop
            </button>
          ) : (
            <button style={smallButtonStyle} onClick={send} disabled={!draft.trim()}>
              Send
            </button>
          )}
        </div>
      </div>
    </div>
  );
});

/**
 * The "/" command menu: shown while the draft is a bare "/prefix" (no space
 * yet), filtered as you type; click (or Tab) inserts the command. Shared by
 * both chat panels — each passes its own command set.
 */
export function SlashMenu({
  draft,
  commands,
  onPick,
}: {
  draft: string;
  commands: SlashCommandInfo[];
  onPick: (text: string) => void;
}) {
  if (!draft.startsWith("/") || /\s/.test(draft)) return null;
  const q = draft.slice(1).toLowerCase();
  const hits = commands.filter((c) => c.name.startsWith(q));
  if (hits.length === 0) return null;
  return (
    <div style={slashMenuStyle}>
      <div style={slashHintStyle}>Commands run their tool directly — no model round. Tab completes.</div>
      {hits.map((c) => (
        <button
          key={c.name}
          style={slashItemStyle}
          // onMouseDown (not click) so the textarea keeps focus for typing the args.
          onMouseDown={(e) => {
            e.preventDefault();
            onPick(`/${c.name} `);
          }}
        >
          <code style={slashCodeStyle}>
            /{c.name}
            {c.args ? ` ${c.args}` : ""}
          </code>
          <span style={{ opacity: 0.65 }}>{c.description}</span>
        </button>
      ))}
    </div>
  );
}

/** Tab-completion for a bare "/prefix" draft; undefined when nothing applies. */
export function completeSlash(draft: string, commands: SlashCommandInfo[]): string | undefined {
  if (!draft.startsWith("/") || /\s/.test(draft)) return undefined;
  const hit = commands.find((c) => c.name.startsWith(draft.slice(1).toLowerCase()));
  return hit ? `/${hit.name} ` : undefined;
}

const slashMenuStyle = {
  borderTop: "1px solid rgba(255,255,255,0.1)",
  maxHeight: 220,
  overflowY: "auto",
  display: "flex",
  flexDirection: "column",
} as const;

const slashHintStyle = {
  fontSize: 10,
  opacity: 0.5,
  padding: "6px 12px 2px",
} as const;

const slashItemStyle = {
  display: "flex",
  gap: 10,
  alignItems: "baseline",
  background: "transparent",
  color: "inherit",
  border: "none",
  textAlign: "left",
  padding: "5px 12px",
  fontSize: 12,
  cursor: "pointer",
} as const;

const slashCodeStyle = {
  color: "#9db8ff",
  whiteSpace: "nowrap",
  fontSize: 12,
} as const;

/** Collapsible context-usage readout — a one-line summary that expands to the
 * donut + legend. Shared by both chat panels. */
export const UsageDisclosure = memo(function UsageDisclosure({ usage }: { usage: ContextUsage }) {
  const pct =
    usage.maxTokens !== undefined
      ? ` · ${Math.min(100, Math.round((usage.approxTokens / usage.maxTokens) * 100))}% of window`
      : "";
  const used = usage.approxTokens >= 1000 ? `${(usage.approxTokens / 1000).toFixed(1)}k` : usage.approxTokens;
  return (
    <details style={usageDetailsStyle}>
      <summary style={usageSummaryStyle}>
        Context: ~{used} tokens{pct} — see breakdown
      </summary>
      <div style={{ padding: "6px 10px 10px" }}>
        <ContextUsageDonut usage={usage} />
      </div>
    </details>
  );
});

const usageDetailsStyle = { borderBottom: "1px solid rgba(255,255,255,0.08)" } as const;
const usageSummaryStyle = {
  cursor: "pointer",
  fontSize: 11,
  opacity: 0.7,
  padding: "6px 12px",
  listStyle: "revert",
} as const;

// Memoised: every keystroke in the draft (panel-local state) and every streamed
// token re-renders the panel — settled bubbles (which can hold images and link
// lists, and grow without bound over a session) must not re-render with it.
// Exported for the landing-page buddy panel, which renders the same bubbles.
// `onDelete(index)` must be a STABLE callback for the same reason — a per-bubble
// closure would defeat the memo.
export const MessageBubble = memo(function MessageBubble({
  message,
  index,
  onDelete,
  onOpenLocalFile,
}: {
  message: ChatMessageVM;
  index?: number;
  onDelete?: (index: number) => void;
  /** Open a local-file result (desktop `/find`). Stable callback (memo). */
  onOpenLocalFile?: (path: string) => void;
}) {
  const isUser = message.role === "user";
  const url = useMessageImageUrl(message.image);
  return (
    <div
      style={{
        ...bubbleStyle,
        alignSelf: isUser ? "flex-end" : "flex-start",
        background: isUser ? "rgba(122,162,255,0.18)" : "rgba(255,255,255,0.06)",
      }}
    >
      {onDelete !== undefined && index !== undefined && (
        <button
          style={deleteButtonStyle}
          title="Delete this message (it leaves the conversation the model sees too)"
          aria-label="Delete message"
          onClick={() => onDelete(index)}
        >
          ✕
        </button>
      )}
      {message.text ? <div style={{ whiteSpace: "pre-wrap" }}>{message.text}</div> : null}
      {url ? (
        <img src={url} alt="Chat image" decoding="async" style={{ maxWidth: "100%", borderRadius: 6, marginTop: message.text ? 6 : 0 }} />
      ) : null}
      {message.links?.length ? (
        <ol style={{ margin: "6px 0 0", paddingLeft: 18, fontSize: 11 }}>
          {message.links.map((l, i) => (
            <li key={i}>
              <a href={l.url} target="_blank" rel="noreferrer" style={{ color: "#9db8ff" }}>
                {l.title || l.url}
              </a>
            </li>
          ))}
        </ol>
      ) : null}
      {message.files?.length ? (
        <div style={{ display: "flex", flexDirection: "column", gap: 4, marginTop: 6 }}>
          {message.files.map((f, i) => (
            <button
              key={i}
              style={fileChipStyle}
              title={`Open ${f.path}`}
              onClick={() => onOpenLocalFile?.(f.path)}
            >
              📄 {f.name}
            </button>
          ))}
        </div>
      ) : null}
    </div>
  );
});

const fileChipStyle = {
  display: "block",
  textAlign: "left",
  background: "rgba(255,255,255,0.06)",
  color: "inherit",
  border: "1px solid rgba(255,255,255,0.18)",
  borderRadius: 6,
  padding: "5px 8px",
  fontSize: 12,
  cursor: "pointer",
} as const;

/** Object URL for a bytes image (revoked on change); pass-through for hotlinks. */
function useMessageImageUrl(image: ChatMessageVM["image"]): string | undefined {
  const bytes = image && "bytes" in image ? image : undefined;
  const [url, setUrl] = useState<string | undefined>(undefined);
  useEffect(() => {
    if (!bytes) {
      setUrl(undefined);
      return;
    }
    const objectUrl = URL.createObjectURL(new Blob([bytes.bytes], { type: bytes.mimeType }));
    setUrl(objectUrl);
    return () => URL.revokeObjectURL(objectUrl);
  }, [bytes]);
  if (image && "sourceUrl" in image) return image.sourceUrl;
  return url;
}

const overlayStyle = {
  position: "fixed",
  inset: 0,
  background: "rgba(0,0,0,0.5)",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  zIndex: 60,
} as const;

const panelStyle = {
  width: "min(680px, 94vw)",
  height: "min(78vh, 720px)",
  background: "#16181d",
  color: "#e6e6e6",
  border: "1px solid rgba(255,255,255,0.12)",
  borderRadius: 10,
  display: "flex",
  flexDirection: "column",
  overflow: "hidden",
} as const;

const headerStyle = {
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "10px 12px",
  borderBottom: "1px solid rgba(255,255,255,0.1)",
} as const;

const scrollStyle = {
  flex: 1,
  overflowY: "auto",
  display: "flex",
  flexDirection: "column",
  gap: 8,
  padding: 12,
} as const;

const bubbleStyle = {
  maxWidth: "85%",
  padding: "8px 10px",
  borderRadius: 8,
  fontSize: 13,
  lineHeight: 1.45,
  position: "relative",
} as const;

const deleteButtonStyle = {
  position: "absolute",
  top: 2,
  right: 2,
  background: "transparent",
  color: "inherit",
  border: "none",
  fontSize: 10,
  opacity: 0.35,
  cursor: "pointer",
  padding: "2px 4px",
} as const;

const approvalStyle = {
  alignSelf: "flex-start",
  border: "1px solid rgba(122,162,255,0.5)",
  borderRadius: 8,
  padding: 10,
  background: "rgba(122,162,255,0.08)",
} as const;

const inputRowStyle = {
  display: "flex",
  gap: 8,
  padding: 10,
  borderTop: "1px solid rgba(255,255,255,0.1)",
  alignItems: "flex-end",
} as const;

const textareaStyle = {
  flex: 1,
  resize: "none",
  background: "rgba(255,255,255,0.06)",
  color: "inherit",
  border: "1px solid rgba(255,255,255,0.15)",
  borderRadius: 6,
  padding: 8,
  fontSize: 13,
  fontFamily: "inherit",
} as const;

const smallButtonStyle = {
  background: "rgba(255,255,255,0.08)",
  color: "inherit",
  border: "1px solid rgba(255,255,255,0.2)",
  borderRadius: 6,
  padding: "6px 10px",
  fontSize: 12,
  cursor: "pointer",
} as const;
