import { memo, useEffect, useRef, useState } from "react";
import {
  CHAT_SLASH_COMMANDS,
  chartDatasetFromTable,
  hasDocImages,
  parseDocImages,
  type AnalyzeChart,
  type ContextUsage,
  type DataTable,
  type ProjectFile,
  type SlashCommandInfo,
  type ToolCall,
} from "@visual-reader/core";
import { ContextUsageDonut } from "./ContextUsageDonut.js";
import { DataChart } from "./DataChart.js";
import { DataTablePreview } from "./DataTablePreview.js";
import { DocBlocksView } from "./DocBlocksView.js";

/**
 * The reading-companion chat panel. Pure presentation: messages, a streaming
 * bubble, inline tool results (search links / images), and the approval bubble
 * for a pending generate_image call — all state lives in the App, which talks to
 * the engine worker. Memoised so token-rate updates re-render only this panel.
 */

export interface ChatMessageVM {
  role: "user" | "assistant" | "tool";
  text: string;
  /** A grounded analyze_data result table (rendered inline, with an optional chart). */
  analysis?: { table: DataTable; summary?: string; chart?: AnalyzeChart };
  /** Inline image: generated bytes, a hotlinkable retrieved figure, or a byte-less `{ id }` reference
   * (bytes externalized to the chat blob store) shown blank until re-hydrated on demand. */
  image?:
    | { bytes: ArrayBuffer; mimeType: string; id?: string }
    | { sourceUrl: string }
    | { id: string; mimeType: string };
  /** Inline video: an image-to-video render's output clip (mp4 / animated webp), shown as a looping player. */
  video?: { bytes: ArrayBuffer; mimeType: string };
  /** Source links from a search tool. */
  links?: { url: string; title?: string }[];
  /** Retrieved images shown as an inline thumbnail gallery (multi-hit search_images);
   * each thumbnail enlarges in place on click. */
  gallery?: { thumb: string; full: string; title?: string }[];
  /** Clickable local-file results (desktop `/find`); each opens the book on click. */
  files?: { path: string; name: string }[];
  /** Files surfaced by the turn (created OR found) shown as a universal file card with
   * Download / Open in app / Open in library / Open on PC actions. */
  attachments?: FileRef[];
  /** Quick-reply action buttons (e.g. what to do with a pasted link). */
  actions?: { label: string; send: string }[];
  /** The model's reasoning for this turn, shown as a collapsed "Reasoning" disclosure. */
  thinking?: string;
}

/** A file surfaced in chat — something the assistant created (a code block, a spreadsheet, an
 * export, a generated image) or something found (a `/find` hit on the PC). The universal file
 * card offers the same actions for all of them; which apply is derived from `kind` + platform. */
export interface FileRef {
  name: string;
  mime: string;
  kind: "code" | "doc" | "data" | "image" | "video" | "text" | "found" | "export";
  /** In-chat text/code content the assistant authored. */
  content?: string;
  /** Raw bytes (a generated image, an exported document). */
  bytes?: ArrayBuffer;
  /** A path to a file already on the user's computer (a desktop `/find` result). */
  path?: string;
  /** Stable id for a bytes-bearing card, so a linked phone can fetch the bytes back from the desktop
   * on demand after the mirror stripped them to stay tunnel-safe. */
  id?: string;
}

/** The four universal file-card actions, wired once by the app and reused for every surfaced file.
 * Each is optional; the card only renders the ones provided (and the ones that fit the file/platform). */
export interface FileActions {
  /** Save a copy — a browser download on the web, the exports folder on desktop (returns the path). */
  download?: (file: FileRef) => Promise<string | true>;
  /** Open the file's content/path in the reader (import → open). */
  openInApp?: (file: FileRef) => void;
  /** Add it to the library and open it. */
  openInLibrary?: (file: FileRef) => void;
  /** Desktop: open it in the OS default app (saving a copy first when it's in-chat content). */
  openOnPC?: (file: FileRef) => void;
  /** Re-open the SAME file through a different reader ("Open as…"): the plain-text reader, the data
   * grid, the book/article reader, or the photo tools. Lets the reader override the extension's route. */
  openAs?: (file: FileRef, as: "reader" | "data" | "text" | "image") => void;
}

/** The "Open as…" choices a file can be re-routed through, with labels for the menu. */
const OPEN_AS_CHOICES: { as: "reader" | "data" | "text" | "image"; label: string }[] = [
  { as: "reader", label: "Open as book / article" },
  { as: "data", label: "Open as spreadsheet / data" },
  { as: "text", label: "Open as plain text" },
  { as: "image", label: "Open as image" },
];

export type MessageBlock =
  | { type: "text"; text: string }
  | { type: "code"; lang: string; code: string; filename?: string };

/** Split a message into prose and fenced ```code``` blocks (saveable as files). The
 * fence's info string may carry a filename after the language (```html index.html`,
 * ```js src/app.js`, or just ```index.html`) so a multi-file answer keeps real names. */
export function parseMessageBlocks(text: string): MessageBlock[] {
  const blocks: MessageBlock[] = [];
  const re = /```([^\n`]*)\r?\n([\s\S]*?)```/g;
  let last = 0;
  for (const m of text.matchAll(re)) {
    const i = m.index;
    if (i > last) blocks.push({ type: "text", text: text.slice(last, i) });
    const { lang, filename } = parseFenceInfo(m[1] ?? "");
    blocks.push({ type: "code", lang, code: m[2]!.replace(/\n$/, ""), ...(filename ? { filename } : {}) });
    last = i + m[0].length;
  }
  if (last < text.length) blocks.push({ type: "text", text: text.slice(last) });
  return blocks.length ? blocks : [{ type: "text", text }];
}

const looksLikeFilename = (s: string): boolean => /[^/\s]+\.[A-Za-z0-9]+$/.test(s) || s.includes("/");

/** Parse a fence info string into a language + optional filename, tolerating
 * `lang filename`, `lang title="filename"`, and a bare `filename`. */
export function parseFenceInfo(info: string): { lang: string; filename?: string } {
  const tokens = info.trim().split(/\s+/).filter(Boolean);
  if (tokens.length === 0) return { lang: "" };
  const cleaned = tokens.map((t) =>
    t.replace(/^(?:title|name|file|filename)=/i, "").replace(/^["']|["']$/g, ""),
  );
  // A bare `filename.ext` as the first token: derive the language from its extension.
  if (looksLikeFilename(cleaned[0]!) && !LANG_EXT[tokens[0]!.toLowerCase()]) {
    return { lang: (cleaned[0]!.split(".").pop() ?? "").toLowerCase(), filename: cleaned[0]! };
  }
  const lang = tokens[0]!.toLowerCase();
  const filename = cleaned.slice(1).find(looksLikeFilename);
  return filename ? { lang, filename } : { lang };
}

/** Resolve a code block's display filename + save name (basename) + mime, preferring
 * an explicit fence filename over the language's generic default. */
export function resolveCodeFile(lang: string, filename?: string): { filename: string; saveName: string; mime: string } {
  if (filename) {
    const ext = (filename.split(".").pop() ?? "").toLowerCase();
    const base = filename.split("/").pop() || filename;
    return { filename, saveName: base, mime: fileForLang(ext).mime };
  }
  const { ext, base, mime } = fileForLang(lang);
  return { filename: `${base}.${ext}`, saveName: `${base}.${ext}`, mime };
}

/** Collect a message's code blocks into project files (named for the zip). */
export function projectFilesFromBlocks(blocks: MessageBlock[]): ProjectFile[] {
  return blocks
    .filter((b): b is Extract<MessageBlock, { type: "code" }> => b.type === "code")
    .map((b) => ({ name: b.filename ?? resolveCodeFile(b.lang, b.filename).filename, content: b.code }));
}

/** What each parsed block should RENDER as: prose `text`, a saveable `file` card, or an inline read-only
 * `snippet`. Snippets are the fix for document fragmentation — a research doc full of illustrative code
 * examples used to shatter into one saveable "file" card per fence. */
export type BlockKind = "text" | "file" | "snippet";

/** A bare (un-named) sole code block at least this big reads as "the file the model just made" (e.g. a
 * whole HTML page); smaller un-named blocks are illustrative snippets and render inline. */
const SAVEABLE_SOLE_MIN_CHARS = 400;

/**
 * Decide, per block, whether a fenced code block is a SAVEABLE FILE or an inline SNIPPET — so a document
 * with embedded examples stops fragmenting into many file cards. A block is a file when it (a) carries a
 * filename hint (the model named it), or (b) is the SOLE code block and DOMINATES the reply (more code
 * than prose, and non-trivial) — i.e. the "here's the whole file" answer. Everything else is an inline
 * snippet. Genuine multi-file answers (several filename-tagged blocks) stay files. PURE. */
export function classifyBlocks(blocks: MessageBlock[]): BlockKind[] {
  const code = blocks.filter((b): b is Extract<MessageBlock, { type: "code" }> => b.type === "code");
  const codeChars = code.reduce((n, b) => n + b.code.length, 0);
  const proseChars = blocks.reduce((n, b) => n + (b.type === "text" ? b.text.trim().length : 0), 0);
  const soleDominant = code.length === 1 && codeChars >= proseChars && codeChars >= SAVEABLE_SOLE_MIN_CHARS;
  return blocks.map((b): BlockKind => {
    if (b.type === "text") return "text";
    if (b.filename) return "file";
    return soleDominant ? "file" : "snippet";
  });
}

/** An HTML block that asks the app to generate + embed images → render as a DocumentCard. */
function isDocBlock(b: Extract<MessageBlock, { type: "code" }>): boolean {
  return (b.lang === "html" || b.lang === "htm" || (b.filename ?? "").endsWith(".html")) && hasDocImages(b.code);
}

/** Generate a designed document's images and return the self-contained HTML. */
export type BuildDocumentFn = (
  html: string,
  onProgress?: (done: number, total: number) => void,
) => Promise<{ html: string; generated: number; failed: number }>;

/** Result of running a code block (Python/JS/shell) — its captured output, or an error. */
export interface RunCodeResult {
  stdout?: string;
  stderr?: string;
  code?: number;
  error?: string;
  /** The directory the code actually ran in, so the reader sees WHERE it executed. */
  cwd?: string;
}
/** Run a code block on the host (the desktop; relayed from a linked phone) and return its output. */
export type RunCodeFn = (lang: string, code: string, filename?: string) => Promise<RunCodeResult>;

const LANG_EXT: Record<string, string> = {
  html: "html", htm: "html", xml: "xml", svg: "svg", css: "css",
  javascript: "js", js: "js", jsx: "jsx", typescript: "ts", ts: "ts", tsx: "tsx",
  python: "py", py: "py", json: "json", csv: "csv", tsv: "tsv",
  markdown: "md", md: "md", yaml: "yaml", yml: "yml", sql: "sql",
  sh: "sh", bash: "sh", shell: "sh", java: "java", c: "c", cpp: "cpp", "c++": "cpp",
  cs: "cs", go: "go", rust: "rs", rs: "rs", rb: "rb", ruby: "rb", php: "php", toml: "toml", ini: "ini",
  pine: "pine", pinescript: "pine", thinkscript: "ts", tos: "ts",
};
/** Extension + a friendly default base name for a code block's language. */
export function fileForLang(lang: string): { ext: string; base: string; mime: string } {
  const ext = LANG_EXT[lang] ?? (lang && /^[a-z0-9]{1,5}$/.test(lang) ? lang : "txt");
  const base =
    ext === "html" ? "page" : ext === "csv" || ext === "tsv" ? "sheet" : ext === "md" ? "document" : "file";
  const mime =
    ext === "html" ? "text/html" :
    ext === "csv" ? "text/csv" :
    ext === "json" ? "application/json" :
    ext === "svg" ? "image/svg+xml" :
    ext === "md" ? "text/markdown" :
    "text/plain";
  return { ext, base, mime };
}

export type LinkSegment = { text: string } | { url: string; label?: string };

/**
 * Split text into plain runs and links. Markdown links `[label](url)` become a
 * single labeled link (so a model that writes `[Title](https://…long…url)` shows a
 * tidy "Title" instead of the raw bracketed URL); bare http(s) URLs in the
 * remaining prose are linkified too.
 */
export function linkifyText(text: string): LinkSegment[] {
  const out: LinkSegment[] = [];
  const md = /\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g;
  let last = 0;
  for (const m of text.matchAll(md)) {
    const i = m.index;
    if (i > last) scanBareUrls(text.slice(last, i), out);
    out.push({ url: m[2]!, label: m[1]! });
    last = i + m[0].length;
  }
  if (last < text.length) scanBareUrls(text.slice(last), out);
  return out;
}

/** Push plain runs + bare http(s) URLs of `text` into `out`. */
function scanBareUrls(text: string, out: LinkSegment[]): void {
  const re = /https?:\/\/[^\s<>"')\]]+/g;
  let last = 0;
  for (const m of text.matchAll(re)) {
    const i = m.index;
    if (i > last) out.push({ text: text.slice(last, i) });
    // Trailing sentence punctuation isn't part of the URL.
    const raw = m[0].replace(/[.,;:!?]+$/, "");
    out.push({ url: raw });
    if (raw.length < m[0].length) out.push({ text: m[0].slice(raw.length) });
    last = i + m[0].length;
  }
  if (last < text.length) out.push({ text: text.slice(last) });
}

export interface ChatPanelProps {
  title: string;
  messages: ChatMessageVM[];
  /** In-flight assistant text (streaming providers), shown as a live bubble. */
  streamingText?: string;
  /** A thinking model's live reasoning (shown dimmed/collapsible while it works). */
  thinking?: string;
  busy: boolean;
  /** Transient activity line ("searching the web…"). */
  activity?: string;
  /** An un-executed generate_image awaiting the reader's approval. */
  pendingTool?: ToolCall;
  allowSpoilers: boolean;
  /** Technical books always see the whole text — hides the spoiler toggle. */
  technical: boolean;
  onSend: (text: string) => void;
  onApprovePendingTool: () => void;
  onDismissPendingTool: () => void;
  onToggleSpoilers: (v: boolean) => void;
  onCancel: () => void;
  onClose: () => void;
  onClearHistory: () => void;
  /** Delete one message by index (must be referentially stable — see MessageBubble). */
  onDeleteMessage?: (index: number) => void;
  /** Compact the conversation into a summary (frees the model's context window). */
  onCompact?: () => void;
  /** Save a file the assistant wrote in a code block. */
  onSaveFile?: (filename: string, content: string, mime: string) => Promise<string | true>;
  /** Run a code block (Python/JS/shell) on the host and show its output. */
  onRunCode?: RunCodeFn;
  /** Zip + save a multi-file (≥2 code blocks) answer as one project. */
  onSaveProject?: (files: ProjectFile[]) => Promise<string | true>;
  /** Generate + embed a designed document's images. */
  onBuildDocument?: BuildDocumentFn;
  /** Download a grounded analysis-result table as a real .xlsx / .csv (host builds it). */
  onDownloadData?: (table: DataTable, name: string, format: "xlsx" | "csv") => void;
  /** Universal file-card actions (Download / Open in app / Open in library / Open on PC). */
  fileActions?: FileActions;
  /** Desktop build — enables the Open-on-PC file action. */
  desktop?: boolean;
  /** Latest context-usage breakdown (for the usage donut). */
  contextUsage?: ContextUsage;
}

export const ChatPanel = memo(function ChatPanel(props: ChatPanelProps) {
  const [draft, setDraft] = useState("");
  const [showHelp, setShowHelp] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);
  // Follow the conversation: stick to the bottom as messages/tokens arrive.
  useEffect(() => {
    const el = scrollRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [props.messages.length, props.streamingText, props.pendingTool, props.activity]);

  const send = () => {
    const text = draft.trim();
    if (!text || props.busy) return;
    setDraft("");
    props.onSend(text);
  };

  return (
    <div style={overlayStyle}>
      <div style={panelStyle}>
        <div style={headerStyle}>
          <strong style={{ fontSize: 14 }}>Chat · {props.title}</strong>
          <span style={{ marginLeft: "auto", display: "flex", gap: 8, alignItems: "center" }}>
            {!props.technical && (
              <label style={{ display: "flex", gap: 4, alignItems: "center", fontSize: 11, opacity: 0.8 }}>
                <input
                  type="checkbox"
                  checked={props.allowSpoilers}
                  onChange={(e) => props.onToggleSpoilers(e.target.checked)}
                />
                allow spoilers (whole book)
              </label>
            )}
            {props.onCompact && props.messages.length > 4 && (
              <button
                style={smallButtonStyle}
                onClick={props.onCompact}
                disabled={props.busy}
                title="Summarize the conversation so far and continue from the summary (frees the model's memory)"
              >
                Compact
              </button>
            )}
            <button
              style={smallButtonStyle}
              onClick={() => setShowHelp((h) => !h)}
              title="What can this chat do? (commands & tools)"
              aria-label="Help"
            >
              ?
            </button>
            <button style={smallButtonStyle} onClick={props.onClearHistory} title="Clear this book's chat history">
              Clear
            </button>
            <button style={smallButtonStyle} onClick={props.onClose}>
              Close
            </button>
          </span>
        </div>

        {props.contextUsage && <UsageDisclosure usage={props.contextUsage} />}
        {showHelp && (
          <CommandHelp
            commands={CHAT_SLASH_COMMANDS}
            intro="Ask in plain language — I'll use these tools when they help. You can also run any of them directly by typing the command:"
          />
        )}

        <div ref={scrollRef} style={scrollStyle}>
          {props.messages.length === 0 && !props.streamingText && (
            <div style={{ opacity: 0.55, fontSize: 12, padding: 12 }}>
              Ask about what you’re reading — characters, concepts, “find a diagram of…”,
              or “draw …, 20 steps, flux 2”.{" "}
              {props.technical
                ? "This technical book is fully visible to the chat."
                : "The chat only knows the book up to your current position (toggle spoilers above)."}
            </div>
          )}
          {props.messages.map((m, i) => (
            <MessageBubble
              {...(props.onRunCode ? { onRunCode: props.onRunCode } : {})}
              key={i}
              message={m}
              index={i}
              {...(props.onDeleteMessage ? { onDelete: props.onDeleteMessage } : {})}
              {...(props.onSaveFile ? { onSaveFile: props.onSaveFile } : {})}
              {...(props.onSaveProject ? { onSaveProject: props.onSaveProject } : {})}
              {...(props.onBuildDocument ? { onBuildDocument: props.onBuildDocument } : {})}
              {...(props.onDownloadData ? { onDownloadData: props.onDownloadData } : {})}
              {...(props.fileActions ? { fileActions: props.fileActions } : {})}
              {...(props.desktop ? { desktop: props.desktop } : {})}
            />
          ))}
          {props.thinking ? <ThinkingBlock text={props.thinking} /> : null}
          {props.streamingText ? (
            <MessageBubble message={{ role: "assistant", text: props.streamingText }} />
          ) : null}
          {props.activity ? (
            <div style={{ opacity: 0.6, fontSize: 12, padding: "2px 8px" }}>{props.activity}</div>
          ) : null}
          {props.pendingTool?.tool === "generate_image" && (
            <div style={approvalStyle}>
              <div style={{ fontSize: 12, marginBottom: 6 }}>
                Generate this image?
                <span style={{ display: "block", opacity: 0.7, marginTop: 2 }}>
                  “{props.pendingTool.prompt}”
                  {props.pendingTool.model ? ` · model: ${props.pendingTool.model}` : ""}
                  {props.pendingTool.steps ? ` · ${props.pendingTool.steps} steps` : ""}
                  {props.pendingTool.style ? ` · style: ${props.pendingTool.style}` : ""}
                </span>
              </div>
              <button style={{ ...smallButtonStyle, marginRight: 6 }} onClick={props.onApprovePendingTool}>
                Run
              </button>
              <button style={smallButtonStyle} onClick={props.onDismissPendingTool}>
                Dismiss
              </button>
            </div>
          )}
        </div>

        <SlashMenu draft={draft} commands={CHAT_SLASH_COMMANDS} onPick={setDraft} />
        <div style={inputRowStyle}>
          <textarea
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                send();
              } else if (e.key === "Tab") {
                const completed = completeSlash(draft, CHAT_SLASH_COMMANDS);
                if (completed) {
                  e.preventDefault();
                  setDraft(completed);
                }
              }
            }}
            placeholder={props.busy ? "Thinking…" : "Ask about the book… (Enter to send, / for commands)"}
            rows={2}
            style={textareaStyle}
          />
          {props.busy ? (
            <button style={smallButtonStyle} onClick={props.onCancel}>
              Stop
            </button>
          ) : (
            <button style={smallButtonStyle} onClick={send} disabled={!draft.trim()}>
              Send
            </button>
          )}
        </div>
      </div>
    </div>
  );
});

/**
 * The "/" command menu: shown while the draft is a bare "/prefix" (no space
 * yet), filtered as you type; click (or Tab) inserts the command. Shared by
 * both chat panels — each passes its own command set.
 */
export function SlashMenu({
  draft,
  commands,
  onPick,
}: {
  draft: string;
  commands: SlashCommandInfo[];
  onPick: (text: string) => void;
}) {
  if (!draft.startsWith("/") || /\s/.test(draft)) return null;
  const q = draft.slice(1).toLowerCase();
  const hits = commands.filter((c) => c.name.startsWith(q));
  if (hits.length === 0) return null;
  return (
    <div style={slashMenuStyle}>
      <div style={slashHintStyle}>Commands run their tool directly — no model round. Tab completes.</div>
      {hits.map((c) => (
        <button
          key={c.name}
          style={slashItemStyle}
          // onMouseDown (not click) so the textarea keeps focus for typing the args.
          onMouseDown={(e) => {
            e.preventDefault();
            onPick(`/${c.name} `);
          }}
        >
          <code style={slashCodeStyle}>
            /{c.name}
            {c.args ? ` ${c.args}` : ""}
          </code>
          <span style={{ opacity: 0.65 }}>{c.description}</span>
        </button>
      ))}
    </div>
  );
}

/**
 * Help card listing everything the chat can do — the same commands the model can
 * use as tools, which you can also invoke directly by typing them. Toggled by the
 * "?" button in either panel's header.
 */
export function CommandHelp({ commands, intro }: { commands: SlashCommandInfo[]; intro: string }) {
  return (
    <div style={helpCardStyle}>
      <div style={{ fontSize: 12, opacity: 0.8, marginBottom: 6 }}>{intro}</div>
      {commands.map((c) => (
        <div key={c.name} style={{ display: "flex", gap: 10, alignItems: "baseline", padding: "3px 0" }}>
          <code style={{ ...slashCodeStyle, minWidth: 132 }}>
            /{c.name}
            {c.args ? ` ${c.args}` : ""}
          </code>
          <span style={{ opacity: 0.7, fontSize: 12 }}>{c.description}</span>
        </div>
      ))}
    </div>
  );
}

const helpCardStyle = {
  borderTop: "1px solid rgba(255,255,255,0.1)",
  borderBottom: "1px solid rgba(255,255,255,0.1)",
  background: "rgba(122,162,255,0.06)",
  padding: "8px 12px",
  maxHeight: 260,
  overflowY: "auto",
} as const;

/** Tab-completion for a bare "/prefix" draft; undefined when nothing applies. */
export function completeSlash(draft: string, commands: SlashCommandInfo[]): string | undefined {
  if (!draft.startsWith("/") || /\s/.test(draft)) return undefined;
  const hit = commands.find((c) => c.name.startsWith(draft.slice(1).toLowerCase()));
  return hit ? `/${hit.name} ` : undefined;
}

const slashMenuStyle = {
  borderTop: "1px solid rgba(255,255,255,0.1)",
  maxHeight: 220,
  overflowY: "auto",
  display: "flex",
  flexDirection: "column",
} as const;

const slashHintStyle = {
  fontSize: 10,
  opacity: 0.5,
  padding: "6px 12px 2px",
} as const;

const slashItemStyle = {
  display: "flex",
  gap: 10,
  alignItems: "baseline",
  background: "transparent",
  color: "inherit",
  border: "none",
  textAlign: "left",
  padding: "5px 12px",
  fontSize: 12,
  cursor: "pointer",
} as const;

const slashCodeStyle = {
  color: "#9db8ff",
  whiteSpace: "nowrap",
  fontSize: 12,
} as const;

/** Collapsible context-usage readout — a one-line summary that expands to the
 * donut + legend. Shared by both chat panels. */
export const UsageDisclosure = memo(function UsageDisclosure({ usage }: { usage: ContextUsage }) {
  const pct =
    usage.maxTokens !== undefined
      ? ` · ${Math.min(100, Math.round((usage.approxTokens / usage.maxTokens) * 100))}% of window`
      : "";
  const used = usage.approxTokens >= 1000 ? `${(usage.approxTokens / 1000).toFixed(1)}k` : usage.approxTokens;
  return (
    <details style={usageDetailsStyle}>
      <summary style={usageSummaryStyle}>
        Context: ~{used} tokens{pct} — see breakdown
      </summary>
      <div style={{ padding: "6px 10px 10px" }}>
        <ContextUsageDonut usage={usage} />
      </div>
    </details>
  );
});

const usageDetailsStyle = { borderBottom: "1px solid rgba(255,255,255,0.08)" } as const;
const usageSummaryStyle = {
  cursor: "pointer",
  fontSize: 11,
  opacity: 0.7,
  padding: "6px 12px",
  listStyle: "revert",
} as const;

// Memoised: every keystroke in the draft (panel-local state) and every streamed
// token re-renders the panel — settled bubbles (which can hold images and link
// lists, and grow without bound over a session) must not re-render with it.
// Exported for the landing-page buddy panel, which renders the same bubbles.
// `onDelete(index)` must be a STABLE callback for the same reason — a per-bubble
// closure would defeat the memo.
export const MessageBubble = memo(function MessageBubble({
  message,
  index,
  onDelete,
  onOpenLocalFile,
  onAction,
  onSaveFile,
  onRunCode,
  onSaveProject,
  onBuildDocument,
  onDownloadData,
  fileActions,
  desktop,
}: {
  message: ChatMessageVM;
  index?: number;
  onDelete?: (index: number) => void;
  /** Open a local-file result (desktop `/find`). Stable callback (memo). */
  onOpenLocalFile?: (path: string) => void;
  /** Run a quick-reply action (sends its text). Stable callback (memo). */
  onAction?: (send: string) => void;
  /** Save a code block the assistant wrote as a file. Stable callback (memo). */
  onSaveFile?: (filename: string, content: string, mime: string) => Promise<string | true>;
  /** Run a code block (Python/JS/shell) on the host. Stable (memo). */
  onRunCode?: RunCodeFn;
  /** Zip + save the message's code blocks as one project (≥2 files). Stable (memo). */
  onSaveProject?: (files: ProjectFile[]) => Promise<string | true>;
  /** Generate + embed a designed document's images. Stable (memo). */
  onBuildDocument?: BuildDocumentFn;
  /** Download a grounded analysis-result table as .xlsx / .csv. Stable (memo). */
  onDownloadData?: (table: DataTable, name: string, format: "xlsx" | "csv") => void;
  /** Universal file-card actions (Download / Open in app / Open in library / Open on PC). Stable (memo). */
  fileActions?: FileActions;
  /** Desktop build — enables the Open-on-PC action. */
  desktop?: boolean;
}) {
  const isUser = message.role === "user";
  const url = useMessageImageUrl(message.image);
  const videoUrl = useMessageVideoUrl(message.video);
  // Assistant prose may contain fenced code blocks (a file the model created) —
  // render those as saveable cards; the user's own messages stay verbatim.
  const blocks = !isUser && message.text ? parseMessageBlocks(message.text) : undefined;
  // Per-block render kind: a saveable file card vs an inline snippet (illustrative code inside a doc) vs
  // prose. Stops a research doc full of examples from shattering into one "file" card per fence.
  const blockKinds = blocks ? classifyBlocks(blocks) : undefined;
  const fileCount = blockKinds?.reduce((n, k) => n + (k === "file" ? 1 : 0), 0) ?? 0;
  return (
    <div
      style={{
        ...bubbleStyle,
        alignSelf: isUser ? "flex-end" : "flex-start",
        background: isUser ? "rgba(122,162,255,0.18)" : "rgba(255,255,255,0.06)",
      }}
    >
      {onDelete !== undefined && index !== undefined && (
        <button
          style={deleteButtonStyle}
          title="Delete this message (it leaves the conversation the model sees too)"
          aria-label="Delete message"
          onClick={() => onDelete(index)}
        >
          ✕
        </button>
      )}
      {!isUser && message.thinking ? <ThinkingBlock text={message.thinking} open={false} label="💭 Reasoning" /> : null}
      {blocks
        ? blocks.map((b, i) =>
            b.type === "code" ? (
              isDocBlock(b) && onBuildDocument ? (
                <DocumentCard
                  key={i}
                  code={b.code}
                  onBuildDocument={onBuildDocument}
                  {...(onSaveFile ? { onSaveFile } : {})}
                />
              ) : blockKinds?.[i] === "snippet" ? (
                // Illustrative code inside a document — read-only inline (copy), NOT a saveable file card.
                <InlineCode key={i} lang={b.lang} code={b.code} />
              ) : (
                <CodeCard
                  key={i}
                  lang={b.lang}
                  code={b.code}
                  {...(b.filename ? { filename: b.filename } : {})}
                  {...(onSaveFile ? { onSaveFile } : {})}
                  {...(onRunCode ? { onRunCode } : {})}
                  {...(fileActions ? { fileActions } : {})}
                  {...(desktop ? { desktop } : {})}
                />
              )
            ) : b.text.trim() ? (
              <div key={i} style={{ whiteSpace: "pre-wrap" }}>
                <Linkified text={b.text} />
              </div>
            ) : null,
          )
        : message.text
          ? (
            <div style={{ whiteSpace: "pre-wrap" }}>
              <Linkified text={message.text} />
            </div>
          )
          : null}
      {fileCount >= 2 && onSaveProject && blocks ? (
        <ProjectSaveBar
          files={projectFilesFromBlocks(blocks.filter((_, i) => blockKinds?.[i] === "file"))}
          onSaveProject={onSaveProject}
        />
      ) : null}
      {url ? (
        <img
          src={url}
          alt="Chat image"
          decoding="async"
          style={{
            display: "block",
            maxWidth: "100%",
            height: "auto", // keep the image's own aspect ratio (never stretched/cropped)
            maxHeight: 420,
            objectFit: "contain",
            borderRadius: 6,
            marginTop: message.text ? 6 : 0,
          }}
        />
      ) : null}
      {videoUrl ? (
        message.video?.mimeType.startsWith("video/") ? (
          <video
            src={videoUrl}
            controls
            autoPlay
            loop
            muted
            playsInline
            style={{ display: "block", maxWidth: "100%", height: "auto", maxHeight: 420, borderRadius: 6, marginTop: message.text ? 6 : 0 }}
          />
        ) : (
          // An animated webp/gif loops natively in an <img> (no <video> controls needed).
          <img
            src={videoUrl}
            alt="Generated animation"
            decoding="async"
            style={{ display: "block", maxWidth: "100%", height: "auto", maxHeight: 420, objectFit: "contain", borderRadius: 6, marginTop: message.text ? 6 : 0 }}
          />
        )
      ) : null}
      {message.analysis ? (
        <AnalysisBlock analysis={message.analysis} {...(onDownloadData ? { onDownloadData } : {})} />
      ) : null}
      {message.gallery?.length ? (
        <ImageGallery items={message.gallery} />
      ) : null}
      {message.links?.length ? (
        <ol style={{ margin: "6px 0 0", paddingLeft: 18, fontSize: 11 }}>
          {message.links.map((l, i) => (
            <li key={i}>
              <a href={l.url} target="_blank" rel="noreferrer" style={{ color: "#9db8ff" }}>
                {l.title || l.url}
              </a>
            </li>
          ))}
        </ol>
      ) : null}
      {message.attachments?.length ? (
        <div style={{ display: "flex", flexDirection: "column", gap: 2, marginTop: 2 }}>
          {message.attachments.map((f, i) =>
            fileActions ? (
              <FileActionBar key={i} file={f} actions={fileActions} label {...(desktop ? { desktop } : {})} />
            ) : null,
          )}
        </div>
      ) : null}
      {message.files?.length ? (
        <div style={{ display: "flex", flexDirection: "column", gap: 4, marginTop: 6 }}>
          {message.files.map((f, i) =>
            // A found PC file: the universal card (Open in app / Download / Open on PC) when wired,
            // else the plain open-on-click chip the desktop /find has always shown.
            fileActions ? (
              <FileActionBar
                key={i}
                file={{ name: f.name, path: f.path, mime: "", kind: "found" }}
                actions={fileActions}
                label
                {...(desktop ? { desktop } : {})}
              />
            ) : (
              <button
                key={i}
                style={fileChipStyle}
                title={`Open ${f.path}`}
                onClick={() => onOpenLocalFile?.(f.path)}
              >
                📄 {f.name}
              </button>
            ),
          )}
        </div>
      ) : null}
      {message.actions?.length ? (
        <div style={{ display: "flex", gap: 6, marginTop: 6, flexWrap: "wrap" }}>
          {message.actions.map((a, i) => (
            <button key={i} style={fileChipStyle} onClick={() => onAction?.(a.send)}>
              {a.label}
            </button>
          ))}
        </div>
      ) : null}
    </div>
  );
});

const fileChipStyle = {
  display: "block",
  textAlign: "left",
  background: "rgba(255,255,255,0.06)",
  color: "inherit",
  border: "1px solid rgba(255,255,255,0.18)",
  borderRadius: 6,
  padding: "5px 8px",
  fontSize: 12,
  cursor: "pointer",
} as const;

const fileMenuStyle = {
  position: "absolute",
  zIndex: 5,
  marginTop: 4,
  display: "flex",
  flexDirection: "column",
  gap: 2,
  background: "#1b1d26",
  border: "1px solid rgba(255,255,255,0.18)",
  borderRadius: 6,
  padding: 4,
  minWidth: 150,
  boxShadow: "0 6px 18px rgba(0,0,0,0.4)",
} as const;

const fileMenuItemStyle = {
  textAlign: "left",
  background: "transparent",
  color: "inherit",
  border: "none",
  borderRadius: 4,
  padding: "5px 8px",
  fontSize: 12,
  cursor: "pointer",
  whiteSpace: "nowrap",
} as const;

type FileActionKey = "dl" | "app" | "lib" | "pc";
type FileActionItem = { key: FileActionKey; label: string; title: string; run: () => void | Promise<unknown> };

/** Which file-card actions apply to a file — pure so it's unit-testable. `has` flags which
 * callbacks the app wired. Rules: Download always (when wired); Open-in-app for everything but a
 * pure export; Open-in-library only for book-like files (not a bare image or export); Open-on-PC
 * desktop-only. Order is stable (download, app, library, pc) so the first stays the inline button. */
export function fileActionKeys(
  kind: FileRef["kind"],
  has: { download?: boolean; openInApp?: boolean; openInLibrary?: boolean; openOnPC?: boolean },
  desktop?: boolean,
): FileActionKey[] {
  const keys: FileActionKey[] = [];
  if (has.download) keys.push("dl");
  if (has.openInApp && kind !== "export") keys.push("app");
  if (has.openInLibrary && kind !== "image" && kind !== "export") keys.push("lib");
  if (desktop && has.openOnPC) keys.push("pc");
  return keys;
}

const FILE_ACTION_LABEL: Record<FileActionKey, { label: string; title: string }> = {
  dl: { label: "💾 Download", title: "Save a copy of this file" },
  app: { label: "📖 Open in app", title: "Open it in the reader" },
  lib: { label: "📚 Open in library", title: "Add it to your library and open it" },
  pc: { label: "🖥 Open on PC", title: "Open it in your computer's default app" },
};

/**
 * The universal file card's action bar — shown under ANY file the assistant created or found:
 * Download, Open in app, Open in library, Open on PC. Only the actions provided AND applicable to
 * the file/platform render; the first stays inline and the rest collapse into a ▾ More dropdown so
 * the row stays compact. One component, reused for code blocks, found files, and surfaced artifacts.
 */
export function FileActionBar({
  file,
  actions,
  desktop,
  label,
}: {
  file: FileRef;
  actions: FileActions;
  desktop?: boolean;
  /** Show the file name as a leading chip (used by the attachments list; off inside a CodeCard). */
  label?: boolean;
}) {
  const [busy, setBusy] = useState<string | undefined>();
  const [readOpen, setReadOpen] = useState(false);
  // A document the chat can render INLINE (read it here without switching to the reader window) — a
  // text/Markdown card that carries its content. Reuses the same block model as the PDF/Word export.
  const canReadInline = !!file.content && (file.mime === "text/markdown" || /\.(md|markdown|txt)$/i.test(file.name));
  const runFor: Record<FileActionKey, () => void | Promise<unknown>> = {
    dl: () => actions.download!(file),
    app: () => actions.openInApp!(file),
    lib: () => actions.openInLibrary!(file),
    pc: () => actions.openOnPC!(file),
  };
  const items: FileActionItem[] = fileActionKeys(
    file.kind,
    { download: !!actions.download, openInApp: !!actions.openInApp, openInLibrary: !!actions.openInLibrary, openOnPC: !!actions.openOnPC },
    desktop,
  ).map((key) => ({ key, ...FILE_ACTION_LABEL[key], run: runFor[key] }));
  if (items.length === 0) return null;
  const fire = async (it: FileActionItem) => {
    setBusy(it.key);
    try {
      await it.run();
    } catch {
      /* the app surfaces its own error note */
    } finally {
      setBusy(undefined);
    }
  };
  const primary = items[0]!;
  const rest = items.slice(1);
  return (
    <div>
    <div style={{ display: "flex", alignItems: "center", gap: 6, marginTop: 6, flexWrap: "wrap" }}>
      {label ? <span style={{ opacity: 0.7, fontSize: 11, marginRight: 2 }}>📎 {file.name}</span> : null}
      <button style={fileChipStyle} title={primary.title} disabled={busy === primary.key} onClick={() => void fire(primary)}>
        {busy === primary.key ? "…" : primary.label}
      </button>
      {canReadInline ? (
        <button
          style={readOpen ? { ...fileChipStyle, borderColor: "rgba(122,162,255,0.6)", color: "#bcd0ff" } : fileChipStyle}
          title="Read this document right here in the chat (no need to open the reader)"
          onClick={() => setReadOpen((v) => !v)}
        >
          {readOpen ? "▾ Hide" : "📖 Read here"}
        </button>
      ) : null}
      {rest.length >= 1 || actions.openAs ? (
        <details style={{ position: "relative" }}>
          <summary style={{ ...fileChipStyle, listStyle: "none", cursor: "pointer" }}>⋯ More</summary>
          <div style={fileMenuStyle}>
            {rest.map((it) => (
              <button key={it.key} style={fileMenuItemStyle} title={it.title} disabled={busy === it.key} onClick={() => void fire(it)}>
                {it.label}
              </button>
            ))}
            {actions.openAs ? (
              <>
                <div style={{ opacity: 0.5, fontSize: 10, padding: "4px 8px 2px" }}>Open as…</div>
                {OPEN_AS_CHOICES.map((c) => (
                  <button key={c.as} style={fileMenuItemStyle} onClick={() => actions.openAs!(file, c.as)}>
                    {c.label}
                  </button>
                ))}
              </>
            ) : null}
          </div>
        </details>
      ) : null}
    </div>
    {canReadInline && readOpen ? (
      <div
        style={{
          maxHeight: 440,
          overflowY: "auto",
          marginTop: 8,
          padding: "12px 16px",
          border: "1px solid rgba(255,255,255,0.12)",
          borderRadius: 8,
          background: "rgba(255,255,255,0.03)",
        }}
      >
        <DocBlocksView markdown={file.content!} />
      </div>
    ) : null}
    </div>
  );
}

/**
 * A row of retrieved-image thumbnails (a multi-hit `search_images`). Every result
 * shows at once — so "show me 3 images of X" actually shows several — and clicking
 * a thumbnail enlarges it in place (no new tab, which the desktop webview blocks).
 */
function ImageGallery({ items }: { items: { thumb: string; full: string; title?: string }[] }) {
  const [enlarged, setEnlarged] = useState<number | null>(null);
  const open = enlarged != null ? items[enlarged] : undefined;
  return (
    <div style={{ marginTop: 6 }}>
      <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
        {items.map((g, i) => (
          <img
            key={i}
            src={g.thumb}
            alt={g.title || "image result"}
            title={g.title || ""}
            loading="lazy"
            decoding="async"
            onClick={() => setEnlarged(enlarged === i ? null : i)}
            style={{
              width: 116,
              height: 116,
              objectFit: "cover",
              borderRadius: 6,
              cursor: enlarged === i ? "zoom-out" : "zoom-in",
              border:
                enlarged === i ? "2px solid #9db8ff" : "1px solid rgba(255,255,255,0.18)",
            }}
          />
        ))}
      </div>
      {open ? (
        <img
          src={open.full}
          alt={open.title || "enlarged image"}
          decoding="async"
          onClick={() => setEnlarged(null)}
          style={{
            display: "block",
            maxWidth: "100%",
            height: "auto",
            maxHeight: 420,
            objectFit: "contain",
            borderRadius: 6,
            marginTop: 6,
            cursor: "zoom-out",
          }}
        />
      ) : null}
    </div>
  );
}

/**
 * A thinking model's live reasoning, shown dimmed and auto-scrolling while it works
 * (so a long reason-before-answering reads as visible progress, not a frozen hang).
 * Collapsible — the reasoning isn't the answer, so it stays out of the way.
 */
export function ThinkingBlock({ text, open = true, label = "💭 Thinking…" }: { text: string; open?: boolean; label?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const el = ref.current;
    if (el && open) el.scrollTop = el.scrollHeight;
  }, [text, open]);
  return (
    <details open={open} style={thinkingStyle}>
      <summary style={{ cursor: "pointer", fontSize: 11, opacity: 0.7 }}>{label}</summary>
      <div
        ref={ref}
        style={{
          whiteSpace: "pre-wrap",
          fontSize: 12,
          opacity: 0.6,
          fontStyle: "italic",
          marginTop: 4,
          maxHeight: 160,
          overflowY: "auto",
        }}
      >
        {text}
      </div>
    </details>
  );
}

const thinkingStyle = {
  alignSelf: "flex-start",
  maxWidth: "92%",
  border: "1px dashed rgba(255,255,255,0.18)",
  borderRadius: 8,
  padding: "6px 10px",
  background: "rgba(255,255,255,0.03)",
} as const;

/**
 * A grounded analyze_data result: the computed table (these numbers are exact — the
 * app calculated them over the real cells), plus an optional chart of the result.
 */
function AnalysisBlock({
  analysis,
  onDownloadData,
}: {
  analysis: { table: DataTable; summary?: string; chart?: AnalyzeChart };
  onDownloadData?: (table: DataTable, name: string, format: "xlsx" | "csv") => void;
}) {
  const { table, chart } = analysis;
  return (
    <div style={{ marginTop: 6 }}>
      <DataTablePreview table={table} maxRows={50} maxHeight={320} />
      {chart ? <AnalysisChart table={table} chart={chart} /> : null}
      {onDownloadData ? (
        <div style={{ display: "flex", gap: 6, marginTop: 6 }}>
          <button style={dataDownloadBtn} title="Download this result as a real Excel workbook" onClick={() => onDownloadData(table, "analysis", "xlsx")}>
            ⬇ Excel
          </button>
          <button style={dataDownloadBtn} title="Download this result as CSV" onClick={() => onDownloadData(table, "analysis", "csv")}>
            ⬇ CSV
          </button>
        </div>
      ) : null}
    </div>
  );
}

const dataDownloadBtn: React.CSSProperties = {
  background: "rgba(90,209,155,0.12)",
  border: "1px solid rgba(90,209,155,0.5)",
  color: "inherit",
  borderRadius: 6,
  padding: "2px 8px",
  fontSize: 11,
  cursor: "pointer",
};

/** Render an analysis result table as a chart by taking its first text + numeric columns. */
function AnalysisChart({ table, chart }: { table: DataTable; chart: AnalyzeChart }) {
  // DataChart supports bar/line/scatter; a requested "pie" falls back to bar.
  const dataset = chartDatasetFromTable(table, chart === "line" ? "line" : "bar", 40);
  if (!dataset) return null;
  return (
    <div style={{ marginTop: 4 }}>
      <DataChart dataset={dataset} />
    </div>
  );
}

/** Inline prose with clickable bare URLs. */
function Linkified({ text }: { text: string }) {
  return (
    <>
      {linkifyText(text).map((seg, i) =>
        "url" in seg ? (
          <a key={i} href={seg.url} target="_blank" rel="noreferrer" style={{ color: "#9db8ff" }}>
            {seg.label ?? seg.url}
          </a>
        ) : (
          <span key={i}>{seg.text}</span>
        ),
      )}
    </>
  );
}

/**
 * A code/content block the assistant wrote (a webpage, a CSV worksheet, a
 * script…), with Save (to disk / download), Copy, and — for HTML — Preview.
 * The model "creates" the file; the user saves it with a click (a real gesture,
 * so browser downloads aren't blocked).
 */
/** An illustrative code snippet inside a document — read-only, with a Copy button but NO save/file
 * actions (it isn't a file the model created, just an example). Keeps a research doc from fragmenting
 * into many saveable "file" cards. */
function InlineCode({ lang, code }: { lang: string; code: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <div style={{ position: "relative", margin: "6px 0" }}>
      <div style={{ ...codeHeaderStyle, opacity: 0.7 }}>
        <span>{lang || "code"}</span>
        <button
          style={codeBtnStyle}
          onClick={() => {
            void navigator.clipboard?.writeText(code);
            setCopied(true);
            setTimeout(() => setCopied(false), 1200);
          }}
        >
          {copied ? "Copied" : "📋 Copy"}
        </button>
      </div>
      <pre style={codePreStyle}>
        <code>{code}</code>
      </pre>
    </div>
  );
}

function CodeCard({
  lang,
  code,
  filename: rawFilename,
  onSaveFile,
  onRunCode,
  fileActions,
  desktop,
}: {
  lang: string;
  code: string;
  filename?: string;
  onSaveFile?: (filename: string, content: string, mime: string) => Promise<string | true>;
  onRunCode?: RunCodeFn;
  /** Universal file-card actions (open in app / library / on PC) for the file this block creates. */
  fileActions?: FileActions;
  desktop?: boolean;
}) {
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState<string | undefined>();
  const [previewOpen, setPreviewOpen] = useState(false);
  const [running, setRunning] = useState(false);
  const [output, setOutput] = useState<RunCodeResult | undefined>();
  const { filename, saveName, mime } = resolveCodeFile(lang, rawFilename);
  const ext = (filename.split(".").pop() ?? "").toLowerCase();
  const previewable = ext === "html" || ext === "svg";
  const l = (lang || "").toLowerCase();
  const runnable = !!onRunCode && (["py", "js", "sh"].includes(ext) || ["python", "js", "javascript", "node", "sh", "bash", "shell"].includes(l));
  const save = async () => {
    if (!onSaveFile) return;
    const r = await onSaveFile(saveName, code, mime);
    setSaved(typeof r === "string" ? r : "saved");
  };
  const run = async () => {
    if (!onRunCode) return;
    setRunning(true);
    setOutput(undefined);
    try {
      setOutput(await onRunCode(lang, code, rawFilename));
    } catch (e) {
      setOutput({ error: e instanceof Error ? e.message : String(e) });
    } finally {
      setRunning(false);
    }
  };
  // Open the rendered page in a new tab (a real click → not blocked).
  const openInTab = () => {
    const url = URL.createObjectURL(new Blob([code], { type: mime }));
    window.open(url, "_blank", "noreferrer");
    setTimeout(() => URL.revokeObjectURL(url), 30_000);
  };
  return (
    <div style={codeCardStyle}>
      <div style={codeHeaderStyle}>
        <span style={{ opacity: 0.7 }}>{lang || "text"} · {filename}</span>
        <span style={{ display: "flex", gap: 6 }}>
          {onSaveFile && (
            <button style={codeBtnStyle} onClick={() => void save()}>
              💾 Save
            </button>
          )}
          {runnable && (
            <button style={codeBtnStyle} onClick={() => void run()} disabled={running} title="Run this code on the desktop and show its output here">
              {running ? "Running…" : "▶ Run"}
            </button>
          )}
          {previewable && (
            <button style={codeBtnStyle} onClick={() => setPreviewOpen((o) => !o)} title="Render it right here in the chat">
              {previewOpen ? "▾ Hide preview" : "▶ Preview"}
            </button>
          )}
          {previewable && (
            <button style={codeBtnStyle} onClick={openInTab} title="Open the rendered page in a new browser tab">
              ↗ Tab
            </button>
          )}
          <button
            style={codeBtnStyle}
            onClick={() => {
              void navigator.clipboard?.writeText(code);
              setCopied(true);
              setTimeout(() => setCopied(false), 1200);
            }}
          >
            {copied ? "Copied" : "📋 Copy"}
          </button>
        </span>
      </div>
      {fileActions ? (
        // The created file's universal actions (Save above is the Download; these add the rest).
        <FileActionBar
          file={{ name: filename, mime, kind: runnable || /^(ts|tsx|js|jsx|py|rb|go|rs|java|c|cpp|sh|css|json)$/.test(ext) ? "code" : "text", content: code }}
          actions={{
            ...(fileActions.openInApp ? { openInApp: fileActions.openInApp } : {}),
            ...(fileActions.openInLibrary ? { openInLibrary: fileActions.openInLibrary } : {}),
            ...(fileActions.openOnPC ? { openOnPC: fileActions.openOnPC } : {}),
          }}
          {...(desktop ? { desktop } : {})}
        />
      ) : null}
      {previewOpen && previewable ? (
        // Sandboxed in-app render: scripts run (so a coded page/widget actually works) but it has no
        // same-origin access — it can't touch the app, cookies, or storage.
        <iframe
          title={`Preview of ${filename}`}
          srcDoc={code}
          sandbox="allow-scripts allow-forms allow-popups allow-modals"
          style={{ width: "100%", height: 320, border: "1px solid rgba(255,255,255,0.12)", borderRadius: 6, background: "#fff" }}
        />
      ) : (
        <pre style={codePreStyle}>
          <code>{code}</code>
        </pre>
      )}
      {output && (
        <pre style={{ ...codePreStyle, borderTop: "1px solid rgba(255,255,255,0.12)", opacity: 0.95 }}>
          <code>
            {output.error
              ? `⚠ ${output.error}`
              : `[exit ${output.code ?? "?"}${output.cwd ? ` · in ${output.cwd}` : ""}]` +
                (output.stdout ? `\n${output.stdout.slice(0, 6000)}` : "") +
                (output.stderr ? `\n⚠ ${output.stderr.slice(0, 3000)}` : "") +
                (!output.stdout && !output.stderr ? "\n(no output)" : "")}
          </code>
        </pre>
      )}
      {saved && (
        <div style={{ fontSize: 11, opacity: 0.7, padding: "4px 8px" }}>
          {saved === "saved" ? "✓ Saved (check your downloads)" : `✓ Saved to ${saved}`}
        </div>
      )}
    </div>
  );
}

/** "Save all as project (.zip)" — appears under a message with ≥2 code blocks, so a
 * linked multi-file answer is kept together (with its relative paths) in one archive. */
function ProjectSaveBar({
  files,
  onSaveProject,
}: {
  files: ProjectFile[];
  onSaveProject: (files: ProjectFile[]) => Promise<string | true>;
}) {
  const [saved, setSaved] = useState<string | undefined>();
  const [busy, setBusy] = useState(false);
  const save = async () => {
    setBusy(true);
    try {
      const r = await onSaveProject(files);
      setSaved(typeof r === "string" ? r : "saved");
    } finally {
      setBusy(false);
    }
  };
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 6, flexWrap: "wrap" }}>
      <button style={codeBtnStyle} onClick={() => void save()} disabled={busy} title={files.map((f) => f.name).join(", ")}>
        📦 {busy ? "Zipping…" : `Save all ${files.length} files as project (.zip)`}
      </button>
      {saved ? (
        <span style={{ fontSize: 11, opacity: 0.7 }}>
          {saved === "saved" ? "✓ Saved (check your downloads)" : `✓ Saved to ${saved}`}
        </span>
      ) : null}
    </div>
  );
}

/** A designed HTML document whose images the app generates and embeds. Shows the
 * source, a "Generate N images & build" action, progress, then Preview + Save of the
 * finished self-contained document. */
function DocumentCard({
  code,
  onBuildDocument,
  onSaveFile,
}: {
  code: string;
  onBuildDocument: BuildDocumentFn;
  onSaveFile?: (filename: string, content: string, mime: string) => Promise<string | true>;
}) {
  const imageCount = parseDocImages(code).length;
  const [building, setBuilding] = useState(false);
  const [progress, setProgress] = useState<{ done: number; total: number }>();
  const [built, setBuilt] = useState<{ html: string; generated: number; failed: number }>();
  const [saved, setSaved] = useState<string | undefined>();
  const [error, setError] = useState("");

  const html = built?.html ?? code;
  const build = async () => {
    setBuilding(true);
    setError("");
    setProgress({ done: 0, total: imageCount });
    try {
      const r = await onBuildDocument(code, (done, total) => setProgress({ done, total }));
      setBuilt(r);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBuilding(false);
      setProgress(undefined);
    }
  };
  const preview = () => {
    const url = URL.createObjectURL(new Blob([html], { type: "text/html" }));
    window.open(url, "_blank", "noreferrer");
    setTimeout(() => URL.revokeObjectURL(url), 30_000);
  };
  const save = async () => {
    if (!onSaveFile) return;
    const r = await onSaveFile("document.html", html, "text/html");
    setSaved(typeof r === "string" ? r : "saved");
  };

  return (
    <div style={codeCardStyle}>
      <div style={codeHeaderStyle}>
        <span style={{ opacity: 0.7 }}>
          🎨 designed document · {imageCount} image{imageCount === 1 ? "" : "s"}
          {built ? ` · ${built.generated} generated${built.failed ? `, ${built.failed} failed` : ""}` : ""}
        </span>
        <span style={{ display: "flex", gap: 6 }}>
          {!built && (
            <button style={codeBtnStyle} onClick={() => void build()} disabled={building}>
              {building
                ? `🎨 Generating ${progress ? `${progress.done}/${progress.total}` : ""}…`
                : `🎨 Generate ${imageCount} image${imageCount === 1 ? "" : "s"} & build`}
            </button>
          )}
          <button style={codeBtnStyle} onClick={preview} disabled={building}>
            ▶ Preview
          </button>
          {onSaveFile && built && (
            <button style={codeBtnStyle} onClick={() => void save()}>
              💾 Save
            </button>
          )}
        </span>
      </div>
      <pre style={codePreStyle}>
        <code>{built ? "<!-- images embedded — Preview or Save the finished document -->" : code}</code>
      </pre>
      {error ? <div style={{ fontSize: 11, color: "#ff9b9b", padding: "4px 8px" }}>{error}</div> : null}
      {saved && (
        <div style={{ fontSize: 11, opacity: 0.7, padding: "4px 8px" }}>
          {saved === "saved" ? "✓ Saved (check your downloads)" : `✓ Saved to ${saved}`}
        </div>
      )}
    </div>
  );
}

const codeCardStyle = {
  border: "1px solid rgba(255,255,255,0.14)",
  borderRadius: 8,
  margin: "6px 0",
  overflow: "hidden",
  background: "rgba(0,0,0,0.25)",
} as const;
const codeHeaderStyle = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  gap: 8,
  padding: "4px 8px",
  fontSize: 11,
  borderBottom: "1px solid rgba(255,255,255,0.1)",
} as const;
const codeBtnStyle = {
  background: "rgba(255,255,255,0.08)",
  color: "inherit",
  border: "1px solid rgba(255,255,255,0.2)",
  borderRadius: 5,
  padding: "2px 6px",
  fontSize: 11,
  cursor: "pointer",
} as const;
const codePreStyle = {
  margin: 0,
  padding: 8,
  maxHeight: 280,
  overflow: "auto",
  fontSize: 12,
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
  whiteSpace: "pre",
} as const;

/** Object URL for a bytes image (revoked on change); pass-through for hotlinks. */
function useMessageImageUrl(image: ChatMessageVM["image"]): string | undefined {
  const bytes = image && "bytes" in image ? image : undefined;
  const [url, setUrl] = useState<string | undefined>(undefined);
  useEffect(() => {
    if (!bytes) {
      setUrl(undefined);
      return;
    }
    const objectUrl = URL.createObjectURL(new Blob([bytes.bytes], { type: bytes.mimeType }));
    setUrl(objectUrl);
    return () => URL.revokeObjectURL(objectUrl);
  }, [bytes]);
  if (image && "sourceUrl" in image) return image.sourceUrl;
  return url;
}

/** Object URL for an inline video clip's bytes (revoked on unmount / change). */
function useMessageVideoUrl(video: ChatMessageVM["video"]): string | undefined {
  const [url, setUrl] = useState<string | undefined>(undefined);
  // Latest clip, read inside the effect — so the effect can rebuild the URL without depending on the
  // `video` object's IDENTITY (see `key` below).
  const videoRef = useRef(video);
  videoRef.current = video;
  // Key the blob URL on the clip's CONTENT (mime + byte size), NOT the object reference. On a linked
  // phone the desktop mirror re-pushes the chat ~8×/sec, rebuilding the message (and its `video`) object
  // each time; keying on identity would revoke + recreate the blob URL under the <video> element on every
  // push, and a URL revoked mid-load leaves the clip blank until a remount (the "only loads after
  // switching away and back" bug). A stable content key creates the URL once and leaves it alone.
  const key = video ? `${video.mimeType}:${video.bytes.byteLength}` : "";
  useEffect(() => {
    const v = videoRef.current;
    if (!v) {
      setUrl(undefined);
      return;
    }
    const objectUrl = URL.createObjectURL(new Blob([v.bytes], { type: v.mimeType }));
    setUrl(objectUrl);
    return () => URL.revokeObjectURL(objectUrl);
  }, [key]);
  return url;
}

const overlayStyle = {
  position: "fixed",
  inset: 0,
  background: "rgba(0,0,0,0.5)",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  zIndex: 60,
} as const;

const panelStyle = {
  width: "min(680px, 94vw)",
  height: "min(78vh, 720px)",
  background: "#16181d",
  color: "#e6e6e6",
  border: "1px solid rgba(255,255,255,0.12)",
  borderRadius: 10,
  display: "flex",
  flexDirection: "column",
  overflow: "hidden",
} as const;

const headerStyle = {
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "10px 12px",
  borderBottom: "1px solid rgba(255,255,255,0.1)",
} as const;

const scrollStyle = {
  flex: 1,
  overflowY: "auto",
  display: "flex",
  flexDirection: "column",
  gap: 8,
  padding: 12,
} as const;

const bubbleStyle = {
  maxWidth: "85%",
  padding: "8px 10px",
  borderRadius: 8,
  fontSize: 13,
  lineHeight: 1.45,
  position: "relative",
} as const;

const deleteButtonStyle = {
  position: "absolute",
  top: 2,
  right: 2,
  background: "transparent",
  color: "inherit",
  border: "none",
  fontSize: 10,
  opacity: 0.35,
  cursor: "pointer",
  padding: "2px 4px",
} as const;

const approvalStyle = {
  alignSelf: "flex-start",
  border: "1px solid rgba(122,162,255,0.5)",
  borderRadius: 8,
  padding: 10,
  background: "rgba(122,162,255,0.08)",
} as const;

const inputRowStyle = {
  display: "flex",
  gap: 8,
  padding: 10,
  borderTop: "1px solid rgba(255,255,255,0.1)",
  alignItems: "flex-end",
} as const;

const textareaStyle = {
  flex: 1,
  resize: "none",
  background: "rgba(255,255,255,0.06)",
  color: "inherit",
  border: "1px solid rgba(255,255,255,0.15)",
  borderRadius: 6,
  padding: 8,
  fontSize: 13,
  fontFamily: "inherit",
} as const;

const smallButtonStyle = {
  background: "rgba(255,255,255,0.08)",
  color: "inherit",
  border: "1px solid rgba(255,255,255,0.2)",
  borderRadius: 6,
  padding: "6px 10px",
  fontSize: 12,
  cursor: "pointer",
} as const;
