import { t } from "./design/tokens.js";
import { memo, useEffect, useMemo, useRef, useState } from "react";
import {
  CHAT_SLASH_COMMANDS,
  chartDatasetFromTable,
  hasDocImages,
  parseDocImages,
  type AnalyzeChart,
  type ContextUsage,
  type DataTable,
  type ProjectFile,
  type SlashCommandInfo,
  type ToolCall,
} from "@visual-reader/core";
import { ContextUsageDonut } from "./ContextUsageDonut.js";
import { DataChart } from "./DataChart.js";
import { DataTablePreview } from "./DataTablePreview.js";
import { DocBlocksView } from "./DocBlocksView.js";
import {
  ACCENT_BLUE,
  DANGER_RED,
  approvalStyle,
  chatHeaderStyle as headerStyle,
  chatInputRowStyle as inputRowStyle,
  chatScrollStyle as scrollStyle,
  chatTextareaStyle as textareaStyle,
  smallButtonStyle,
} from "./tokens.js";
import { cx } from "./design/classes.js";
import { ModalShell } from "./ModalShell.js";
import { ArrivingImage } from "./ArrivingImage.js";

/**
 * The reading-companion chat panel. Pure presentation: messages, a streaming
 * bubble, inline tool results (search links / images), and the approval bubble
 * for a pending generate_image call — all state lives in the App, which talks to
 * the engine worker. Memoised so token-rate updates re-render only this panel.
 */

export interface ChatMessageVM {
  role: "user" | "assistant" | "tool";
  text: string;
  /** Message creation timestamp (ms epoch). Used as a STABLE React key so deleting a message doesn't
   * shift every later bubble's child state (CodeCard output, iframe preview, gallery zoom) onto the
   * wrong message — positional index keys did exactly that. Absent → the render falls back to index. */
  at?: number;
  /** A grounded analyze_data result table (rendered inline, with an optional chart). */
  analysis?: { table: DataTable; summary?: string; chart?: AnalyzeChart };
  /** Inline image: generated bytes, a hotlinkable retrieved figure, or a byte-less `{ id }` reference
   * (bytes externalized to the chat blob store) shown blank until re-hydrated on demand. */
  image?:
    | { bytes: ArrayBuffer; mimeType: string; id?: string }
    | { sourceUrl: string }
    | { id: string; mimeType: string };
  /** Inline video: an image-to-video render's output clip (mp4 / animated webp), shown as a looping player. */
  video?: { bytes: ArrayBuffer; mimeType: string };
  /** Source links from a search tool. */
  links?: { url: string; title?: string }[];
  /** Retrieved images shown as an inline thumbnail gallery (multi-hit search_images);
   * each thumbnail enlarges in place on click. */
  gallery?: { thumb: string; full: string; title?: string }[];
  /** Clickable local-file results (desktop `/find`); each opens the book on click. */
  files?: { path: string; name: string }[];
  /** Files surfaced by the turn (created OR found) shown as a universal file card with
   * Download / Open in app / Open in library / Open on PC actions. */
  attachments?: FileRef[];
  /** Quick-reply action buttons (e.g. what to do with a pasted link). */
  actions?: { label: string; send: string }[];
  /** The model's reasoning for this turn, shown as a collapsed "Reasoning" disclosure. */
  thinking?: string;
}

/** Stable React keys for a chat message list. Keys on each message's `at` timestamp, disambiguating
 * two messages that share a millisecond with an ordinal, and falling back to the index only when `at`
 * is absent. Stable across a delete — the removed message's key simply disappears and every other
 * bubble keeps its key — so a bubble's child state (CodeCard run output, iframe preview, gallery zoom)
 * stays attached to its own message instead of shifting onto a neighbour (U1). */
export function chatMessageKeys(messages: ChatMessageVM[]): string[] {
  const seen = new Map<number, number>();
  return messages.map((m, i) => {
    if (m.at === undefined) return `i${i}`;
    const n = seen.get(m.at) ?? 0;
    seen.set(m.at, n + 1);
    return `t${m.at}-${n}`;
  });
}

/** A file surfaced in chat — something the assistant created (a code block, a spreadsheet, an
 * export, a generated image) or something found (a `/find` hit on the PC). The universal file
 * card offers the same actions for all of them; which apply is derived from `kind` + platform. */
export interface FileRef {
  name: string;
  mime: string;
  kind: "code" | "doc" | "data" | "image" | "video" | "text" | "found" | "export";
  /** In-chat text/code content the assistant authored. */
  content?: string;
  /** Raw bytes (a generated image, an exported document). */
  bytes?: ArrayBuffer;
  /** A path to a file already on the user's computer (a desktop `/find` result). */
  path?: string;
  /** Stable id for a bytes-bearing card, so a linked phone can fetch the bytes back from the desktop
   * on demand after the mirror stripped them to stay tunnel-safe. */
  id?: string;
}

/** The four universal file-card actions, wired once by the app and reused for every surfaced file.
 * Each is optional; the card only renders the ones provided (and the ones that fit the file/platform). */
export interface FileActions {
  /** Save a copy — a browser download on the web, the exports folder on desktop. Returns the PATH it
   * wrote (desktop), `true` for a browser download, or `undefined` when the reader cancelled the
   * name prompt — the bar reports each of those differently, and "cancelled" must not read as saved. */
  download?: (file: FileRef) => Promise<string | true | undefined>;
  /** Open the file's content/path in the reader (import → open). */
  openInApp?: (file: FileRef) => void;
  /** Add it to the library and open it. */
  openInLibrary?: (file: FileRef) => void;
  /** Desktop: open it in the OS default app (saving a copy first when it's in-chat content). */
  openOnPC?: (file: FileRef) => void;
  /** Re-open the SAME file through a different reader ("Open as…"): the plain-text reader, the data
   * grid, the book/article reader, or the photo tools. Lets the reader override the extension's route. */
  openAs?: (file: FileRef, as: "reader" | "data" | "text" | "image") => void;
  /** Fetch a text document's contents so it can be read INLINE in the chat. Only asked for when the
   * card is a text/Markdown file that doesn't already carry its text — a written `.md` surfaced as a
   * bare path, or a card whose bytes were externalized on persist. Resolve `undefined` when the text
   * genuinely can't be got; the card then says so rather than showing an empty document. */
  readText?: (file: FileRef) => Promise<string | undefined>;
}

/** The "Open as…" choices a file can be re-routed through, with labels for the menu. */
const OPEN_AS_CHOICES: { as: "reader" | "data" | "text" | "image"; label: string }[] = [
  { as: "reader", label: "Open as book / article" },
  { as: "data", label: "Open as spreadsheet / data" },
  { as: "text", label: "Open as plain text" },
  { as: "image", label: "Open as image" },
];

export type MessageBlock =
  | { type: "text"; text: string }
  | { type: "code"; lang: string; code: string; filename?: string };

/** Split a message into prose and fenced ```code``` blocks (saveable as files). The
 * fence's info string may carry a filename after the language (```html index.html`,
 * ```js src/app.js`, or just ```index.html`) so a multi-file answer keeps real names. */
export function parseMessageBlocks(text: string): MessageBlock[] {
  const blocks: MessageBlock[] = [];
  const re = /```([^\n`]*)\r?\n([\s\S]*?)```/g;
  let last = 0;
  for (const m of text.matchAll(re)) {
    const i = m.index;
    if (i > last) blocks.push({ type: "text", text: text.slice(last, i) });
    const { lang, filename } = parseFenceInfo(m[1] ?? "");
    blocks.push(
      ...splitRunTogetherFiles({ type: "code", lang, code: m[2]!.replace(/\n$/, ""), ...(filename ? { filename } : {}) }),
    );
    last = i + m[0].length;
  }
  if (last < text.length) blocks.push({ type: "text", text: text.slice(last) });
  return blocks.length ? blocks : [{ type: "text", text }];
}

/** A body line long enough that it's prose, not a fence header someone forgot to fence. */
const MAX_HEADER_LINE = 120;

/**
 * Split ONE code block that is really SEVERAL files run together, because the model wrote the second
 * and third files' fence headers as ordinary lines INSIDE the first block instead of opening new
 * fences.
 *
 * Asked for three haikus as separate documents, a local model produced one ```text haiku_6.txt block
 * whose body was haiku 6, then the bare line `text haiku_7.txt`, then haiku 7, then `text haiku_8.txt`,
 * then haiku 8. The reader gets one file card for three files, and no button in the app can undo that
 * — every downstream feature (Save, Save all as project, Open in app) reads the parsed blocks. Nothing
 * about the model's INTENT is ambiguous here: it named three files, in the exact grammar the fence line
 * uses. So the app reads what was written rather than what was fenced.
 *
 * Deliberately narrow, because a false split silently corrupts a real file. A cut requires all of:
 * the block itself is named (the model was naming files), the line is exactly two tokens, the first is
 * the block's OWN language verbatim, and the second is a filename with an extension. `text haiku_7.txt`
 * inside a ```text haiku_6.txt block is that; a bare `README.md` line — which is ordinary content in a
 * document listing files — is NOT, and is left alone. PURE.
 */
export function splitRunTogetherFiles(
  block: Extract<MessageBlock, { type: "code" }>,
): Extract<MessageBlock, { type: "code" }>[] {
  if (!block.filename || !block.lang) return [block];
  const lines = block.code.split("\n");
  const cuts: { at: number; filename: string }[] = [];
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i]!.trim();
    if (!raw || raw.length > MAX_HEADER_LINE) continue;
    const tokens = raw.split(/\s+/);
    if (tokens.length !== 2 || tokens[0]!.toLowerCase() !== block.lang) continue;
    const name = tokens[1]!;
    if (!/\.[A-Za-z0-9]+$/.test(name)) continue;
    cuts.push({ at: i, filename: name });
  }
  if (cuts.length === 0) return [block];
  const parts: Extract<MessageBlock, { type: "code" }>[] = [];
  const push = (filename: string, from: number, to: number): void => {
    const code = lines.slice(from, to).join("\n").replace(/^\n+|\n+$/g, "");
    if (code.trim()) parts.push({ type: "code", lang: block.lang, code, filename });
  };
  push(block.filename, 0, cuts[0]!.at);
  for (let k = 0; k < cuts.length; k++) {
    push(cuts[k]!.filename, cuts[k]!.at + 1, cuts[k + 1]?.at ?? lines.length);
  }
  // A run of headers with no bodies isn't several files — leave the block as the model wrote it.
  return parts.length > 1 ? parts : [block];
}

const looksLikeFilename = (s: string): boolean => /[^/\s]+\.[A-Za-z0-9]+$/.test(s) || s.includes("/");

/** Parse a fence info string into a language + optional filename, tolerating
 * `lang filename`, `lang title="filename"`, and a bare `filename`. */
export function parseFenceInfo(info: string): { lang: string; filename?: string } {
  const tokens = info.trim().split(/\s+/).filter(Boolean);
  if (tokens.length === 0) return { lang: "" };
  const cleaned = tokens.map((t) =>
    t.replace(/^(?:title|name|file|filename)=/i, "").replace(/^["']|["']$/g, ""),
  );
  // A bare `filename.ext` as the first token: derive the language from its extension.
  if (looksLikeFilename(cleaned[0]!) && !LANG_EXT[tokens[0]!.toLowerCase()]) {
    return { lang: (cleaned[0]!.split(".").pop() ?? "").toLowerCase(), filename: cleaned[0]! };
  }
  const lang = tokens[0]!.toLowerCase();
  const filename = cleaned.slice(1).find(looksLikeFilename);
  return filename ? { lang, filename } : { lang };
}

/** Resolve a code block's display filename + save name (basename) + mime, preferring
 * an explicit fence filename over the language's generic default. */
export function resolveCodeFile(lang: string, filename?: string): { filename: string; saveName: string; mime: string } {
  if (filename) {
    const ext = (filename.split(".").pop() ?? "").toLowerCase();
    const base = filename.split("/").pop() || filename;
    return { filename, saveName: base, mime: fileForLang(ext).mime };
  }
  const { ext, base, mime } = fileForLang(lang);
  return { filename: `${base}.${ext}`, saveName: `${base}.${ext}`, mime };
}

/** Collect a message's code blocks into project files (named for the zip). */
export function projectFilesFromBlocks(blocks: MessageBlock[]): ProjectFile[] {
  return blocks
    .filter((b): b is Extract<MessageBlock, { type: "code" }> => b.type === "code")
    .map((b) => ({ name: b.filename ?? resolveCodeFile(b.lang, b.filename).filename, content: b.code }));
}

/** What each parsed block should RENDER as: prose `text`, a saveable `file` card, or an inline read-only
 * `snippet`. Snippets are the fix for document fragmentation — a research doc full of illustrative code
 * examples used to shatter into one saveable "file" card per fence. */
export type BlockKind = "text" | "file" | "snippet";

/** A bare (un-named) sole code block at least this big reads as "the file the model just made" (e.g. a
 * whole HTML page); smaller un-named blocks are illustrative snippets and render inline. */
const SAVEABLE_SOLE_MIN_CHARS = 400;

/**
 * Decide, per block, whether a fenced code block is a SAVEABLE FILE or an inline SNIPPET — so a document
 * with embedded examples stops fragmenting into many file cards. A block is a file when it (a) carries a
 * filename hint (the model named it), or (b) is the SOLE code block and DOMINATES the reply (more code
 * than prose, and non-trivial) — i.e. the "here's the whole file" answer. Everything else is an inline
 * snippet. Genuine multi-file answers (several filename-tagged blocks) stay files. PURE. */
export function classifyBlocks(blocks: MessageBlock[]): BlockKind[] {
  const code = blocks.filter((b): b is Extract<MessageBlock, { type: "code" }> => b.type === "code");
  const codeChars = code.reduce((n, b) => n + b.code.length, 0);
  const proseChars = blocks.reduce((n, b) => n + (b.type === "text" ? b.text.trim().length : 0), 0);
  const soleDominant = code.length === 1 && codeChars >= proseChars && codeChars >= SAVEABLE_SOLE_MIN_CHARS;
  return blocks.map((b): BlockKind => {
    if (b.type === "text") return "text";
    if (b.filename) return "file";
    return soleDominant ? "file" : "snippet";
  });
}

/** An HTML block that asks the app to generate + embed images → render as a DocumentCard. */
function isDocBlock(b: Extract<MessageBlock, { type: "code" }>): boolean {
  return (b.lang === "html" || b.lang === "htm" || (b.filename ?? "").endsWith(".html")) && hasDocImages(b.code);
}

/** Generate a designed document's images and return the self-contained HTML. */
export type BuildDocumentFn = (
  html: string,
  onProgress?: (done: number, total: number) => void,
) => Promise<{ html: string; generated: number; failed: number }>;

/** Result of running a code block (Python/JS/shell) — its captured output, or an error. */
export interface RunCodeResult {
  stdout?: string;
  stderr?: string;
  code?: number;
  error?: string;
  /** The directory the code actually ran in, so the reader sees WHERE it executed. */
  cwd?: string;
}
/** Run a code block on the host (the desktop; relayed from a linked phone) and return its output. */
export type RunCodeFn = (lang: string, code: string, filename?: string) => Promise<RunCodeResult>;

const LANG_EXT: Record<string, string> = {
  html: "html", htm: "html", xml: "xml", svg: "svg", css: "css",
  javascript: "js", js: "js", jsx: "jsx", typescript: "ts", ts: "ts", tsx: "tsx",
  python: "py", py: "py", json: "json", csv: "csv", tsv: "tsv",
  markdown: "md", md: "md", yaml: "yaml", yml: "yml", sql: "sql",
  sh: "sh", bash: "sh", shell: "sh", java: "java", c: "c", cpp: "cpp", "c++": "cpp",
  cs: "cs", go: "go", rust: "rs", rs: "rs", rb: "rb", ruby: "rb", php: "php", toml: "toml", ini: "ini",
  pine: "pine", pinescript: "pine", thinkscript: "ts", tos: "ts",
};
/** Extension + a friendly default base name for a code block's language. */
export function fileForLang(lang: string): { ext: string; base: string; mime: string } {
  const ext = LANG_EXT[lang] ?? (lang && /^[a-z0-9]{1,5}$/.test(lang) ? lang : "txt");
  const base =
    ext === "html" ? "page" : ext === "csv" || ext === "tsv" ? "sheet" : ext === "md" ? "document" : "file";
  const mime =
    ext === "html" ? "text/html" :
    ext === "csv" ? "text/csv" :
    ext === "json" ? "application/json" :
    ext === "svg" ? "image/svg+xml" :
    ext === "md" ? "text/markdown" :
    "text/plain";
  return { ext, base, mime };
}

export type LinkSegment = { text: string } | { url: string; label?: string };

/**
 * Split text into plain runs and links. Markdown links `[label](url)` become a
 * single labeled link (so a model that writes `[Title](https://…long…url)` shows a
 * tidy "Title" instead of the raw bracketed URL); bare http(s) URLs in the
 * remaining prose are linkified too.
 */
export function linkifyText(text: string): LinkSegment[] {
  const out: LinkSegment[] = [];
  const md = /\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g;
  let last = 0;
  for (const m of text.matchAll(md)) {
    const i = m.index;
    if (i > last) scanBareUrls(text.slice(last, i), out);
    out.push({ url: m[2]!, label: m[1]! });
    last = i + m[0].length;
  }
  if (last < text.length) scanBareUrls(text.slice(last), out);
  return out;
}

/** Push plain runs + bare http(s) URLs of `text` into `out`. */
function scanBareUrls(text: string, out: LinkSegment[]): void {
  const re = /https?:\/\/[^\s<>"')\]]+/g;
  let last = 0;
  for (const m of text.matchAll(re)) {
    const i = m.index;
    if (i > last) out.push({ text: text.slice(last, i) });
    // Trailing sentence punctuation isn't part of the URL.
    const raw = m[0].replace(/[.,;:!?]+$/, "");
    out.push({ url: raw });
    if (raw.length < m[0].length) out.push({ text: m[0].slice(raw.length) });
    last = i + m[0].length;
  }
  if (last < text.length) out.push({ text: text.slice(last) });
}

export interface ChatPanelProps {
  title: string;
  messages: ChatMessageVM[];
  /** In-flight assistant text (streaming providers), shown as a live bubble. */
  streamingText?: string;
  /** A thinking model's live reasoning (shown dimmed/collapsible while it works). */
  thinking?: string;
  /** Whether the reasoning disclosure is open — owned by the HOST so the reader's choice survives the
   * next reply (see ThinkingBlock). */
  thinkingOpen?: boolean;
  onThinkingOpenChange?: (open: boolean) => void;
  busy: boolean;
  /** Transient activity line ("searching the web…"). */
  activity?: string;
  /** An un-executed generate_image awaiting the reader's approval. */
  pendingTool?: ToolCall;
  allowSpoilers: boolean;
  /** Technical books always see the whole text — hides the spoiler toggle. */
  technical: boolean;
  onSend: (text: string) => void;
  onApprovePendingTool: () => void;
  onDismissPendingTool: () => void;
  onToggleSpoilers: (v: boolean) => void;
  onCancel: () => void;
  onClose: () => void;
  onClearHistory: () => void;
  /** Delete one message by index (must be referentially stable — see MessageBubble). */
  onDeleteMessage?: (index: number) => void;
  /** Adopt a searched picture as the reference this session's renders draw from. The book chat shows
   * image results as a gallery exactly like the buddy chat, and was the one panel where a picture in
   * it couldn't be picked up and drawn from — MessageBubble has always supported this; nothing here
   * passed it down. */
  onUseImageAsReference?: (item: { full: string; title?: string }) => void;
  /** Compact the conversation into a summary (frees the model's context window). */
  onCompact?: () => void;
  /** Save a file the assistant wrote in a code block. */
  onSaveFile?: (filename: string, content: string, mime: string) => Promise<string | true>;
  /** Run a code block (Python/JS/shell) on the host and show its output. */
  onRunCode?: RunCodeFn;
  /** Zip + save a multi-file (≥2 code blocks) answer as one project. */
  onSaveProject?: (files: ProjectFile[]) => Promise<string | true>;
  /** Generate + embed a designed document's images. */
  onBuildDocument?: BuildDocumentFn;
  /** Download a grounded analysis-result table as a real .xlsx / .csv (host builds it). */
  onDownloadData?: (table: DataTable, name: string, format: "xlsx" | "csv") => void;
  /** Universal file-card actions (Download / Open in app / Open in library / Open on PC). */
  fileActions?: FileActions;
  /** Open a found-file chip (a /find result on the desktop's disk) as a book. */
  onOpenLocalFile?: (path: string) => void;
  /** Desktop build — enables the Open-on-PC file action. */
  desktop?: boolean;
  /** Latest context-usage breakdown (for the usage donut). */
  contextUsage?: ContextUsage;
}

export const ChatPanel = memo(function ChatPanel(props: ChatPanelProps) {
  const [draft, setDraft] = useState("");
  const [showHelp, setShowHelp] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);
  // Follow the conversation: stick to the bottom as messages/tokens arrive — but only
  // while the reader is already near it, so scrolling up to re-read isn't yanked back.
  // "Was near bottom" is captured in the onScroll handler: the effect runs AFTER render,
  // when scrollHeight has already grown, so it can't measure the pre-update position.
  const nearBottomRef = useRef(true);
  const trackNearBottom = (): void => {
    const el = scrollRef.current;
    if (el) nearBottomRef.current = el.scrollHeight - el.scrollTop - el.clientHeight < 80;
  };
  useEffect(() => {
    const el = scrollRef.current;
    if (el && nearBottomRef.current) el.scrollTop = el.scrollHeight;
  }, [props.messages.length, props.streamingText, props.pendingTool, props.activity]);

  const send = () => {
    const text = draft.trim();
    if (!text || props.busy) return;
    setDraft("");
    props.onSend(text);
  };

  return (
    <ModalShell
      title={`Chat — ${props.title}`}
      onClose={props.onClose}
      overlayStyle={overlayStyle}
      cardStyle={panelStyle}
      disableBackdropClose
    >
        <div style={headerStyle}>
          <strong style={{ fontSize: 14 }} title={props.title}>Chat · {props.title}</strong>
          <span style={{ marginLeft: "auto", display: "flex", gap: 8, alignItems: "center" }}>
            {!props.technical && (
              <label style={{ display: "flex", gap: 4, alignItems: "center", fontSize: 11, opacity: 0.8 }}>
                <input
                  type="checkbox"
                  checked={props.allowSpoilers}
                  onChange={(e) => props.onToggleSpoilers(e.target.checked)}
                />
                allow spoilers (whole book)
              </label>
            )}
            {props.onCompact && props.messages.length > 4 && (
              <button
                style={smallButtonStyle}
                onClick={props.onCompact}
                disabled={props.busy}
                title="Summarize the conversation so far and continue from the summary (frees the model's memory)"
              >
                Compact
              </button>
            )}
            <button
              style={smallButtonStyle}
              onClick={() => setShowHelp((h) => !h)}
              title="What can this chat do? (commands & tools)"
              aria-label="Help"
            >
              ?
            </button>
            <button
              style={smallButtonStyle}
              onClick={() => {
                // Confirm before wiping — the buddy chat's Clear already does; book chat didn't (U5).
                if (window.confirm("Clear this book's chat history? All its messages are removed permanently.")) props.onClearHistory();
              }}
              title="Clear this book's chat history"
            >
              Clear
            </button>
            <button style={smallButtonStyle} onClick={props.onClose}>
              Close
            </button>
          </span>
        </div>

        {props.contextUsage && <UsageDisclosure usage={props.contextUsage} />}
        {showHelp && (
          <CommandHelp
            commands={CHAT_SLASH_COMMANDS}
            intro="Ask in plain language — I'll use these tools when they help. You can also run any of them directly by typing the command:"
          />
        )}

        <div ref={scrollRef} onScroll={trackNearBottom} style={scrollStyle}>
          {props.messages.length === 0 && !props.streamingText && (
            <div style={{ opacity: 0.55, fontSize: 12, padding: 12 }}>
              Ask about what you’re reading — characters, concepts, “find a diagram of…”,
              or “draw …, 20 steps, flux 2”.{" "}
              {props.technical
                ? "This technical book is fully visible to the chat."
                : "The chat only knows the book up to your current position (toggle spoilers above)."}
            </div>
          )}
          {chatMessageKeys(props.messages).map((mkey, i) => {
            const m = props.messages[i]!;
            return (
            <MessageBubble
              {...(props.onRunCode ? { onRunCode: props.onRunCode } : {})}
              key={mkey}
              message={m}
              index={i}
              {...(props.onDeleteMessage ? { onDelete: props.onDeleteMessage } : {})}
              {...(props.onOpenLocalFile ? { onOpenLocalFile: props.onOpenLocalFile } : {})}
              {...(props.onSaveFile ? { onSaveFile: props.onSaveFile } : {})}
              {...(props.onSaveProject ? { onSaveProject: props.onSaveProject } : {})}
              {...(props.onBuildDocument ? { onBuildDocument: props.onBuildDocument } : {})}
              {...(props.onDownloadData ? { onDownloadData: props.onDownloadData } : {})}
              {...(props.fileActions ? { fileActions: props.fileActions } : {})}
              {...(props.onUseImageAsReference ? { onUseImageAsReference: props.onUseImageAsReference } : {})}
              {...(props.desktop ? { desktop: props.desktop } : {})}
              {...(props.thinkingOpen !== undefined && i === props.messages.length - 1
                ? { thinkingOpen: props.thinkingOpen }
                : {})}
              {...(props.onThinkingOpenChange ? { onThinkingOpenChange: props.onThinkingOpenChange } : {})}
              onAction={props.onSend}
            />
            );
          })}
          {props.thinking ? (
            <ThinkingBlock
              text={props.thinking}
              open={props.thinkingOpen ?? true}
              {...(props.onThinkingOpenChange ? { onOpenChange: props.onThinkingOpenChange } : {})}
            />
          ) : null}
          {props.streamingText ? (
            <MessageBubble message={{ role: "assistant", text: props.streamingText }} />
          ) : null}
          {props.activity ? (
            <div style={{ opacity: 0.6, fontSize: 12, padding: "2px 8px" }}>{props.activity}</div>
          ) : null}
          {props.pendingTool?.tool === "generate_image" && (
            <div style={approvalStyle}>
              <div style={{ fontSize: 12, marginBottom: 6 }}>
                Generate this image?
                <span style={{ display: "block", opacity: 0.7, marginTop: 2 }}>
                  “{props.pendingTool.prompt}”
                  {props.pendingTool.model ? ` · model: ${props.pendingTool.model}` : ""}
                  {props.pendingTool.steps ? ` · ${props.pendingTool.steps} steps` : ""}
                  {props.pendingTool.style ? ` · style: ${props.pendingTool.style}` : ""}
                </span>
              </div>
              <button style={{ ...smallButtonStyle, marginRight: 6 }} onClick={props.onApprovePendingTool}>
                Run
              </button>
              <button style={smallButtonStyle} onClick={props.onDismissPendingTool}>
                Dismiss
              </button>
            </div>
          )}
        </div>

        <SlashMenu draft={draft} commands={CHAT_SLASH_COMMANDS} onPick={setDraft} />
        <div style={inputRowStyle}>
          <textarea
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                send();
              } else if (e.key === "Tab") {
                const completed = completeSlash(draft, CHAT_SLASH_COMMANDS);
                if (completed) {
                  e.preventDefault();
                  setDraft(completed);
                }
              }
            }}
            placeholder={props.busy ? "Thinking…" : "Ask about the book… (Enter to send, / for commands)"}
            rows={2}
            style={textareaStyle}
          />
          {props.busy ? (
            <button style={smallButtonStyle} onClick={props.onCancel}>
              Stop
            </button>
          ) : (
            <button style={smallButtonStyle} onClick={send} disabled={!draft.trim()}>
              Send
            </button>
          )}
        </div>
    </ModalShell>
  );
});

/**
 * The "/" command menu: shown while the draft is a bare "/prefix" (no space
 * yet), filtered as you type; click (or Tab) inserts the command. Shared by
 * both chat panels — each passes its own command set.
 */
export function SlashMenu({
  draft,
  commands,
  onPick,
}: {
  draft: string;
  commands: SlashCommandInfo[];
  onPick: (text: string) => void;
}) {
  if (!draft.startsWith("/") || /\s/.test(draft)) return null;
  const q = draft.slice(1).toLowerCase();
  const hits = commands.filter((c) => c.name.startsWith(q));
  if (hits.length === 0) return null;
  return (
    <div style={slashMenuStyle}>
      <div style={slashHintStyle}>Commands run their tool directly — no model round. Tab completes.</div>
      {hits.map((c) => (
        <button
          key={c.name}
          style={slashItemStyle}
          // onMouseDown (not click) so the textarea keeps focus for typing the args;
          // preventDefault also stops the later click, so keyboard activation below
          // (a Tab-focused item) can't double-fire with a mouse pick.
          onMouseDown={(e) => {
            e.preventDefault();
            onPick(`/${c.name} `);
          }}
          onKeyDown={(e) => {
            if (e.key === "Enter" || e.key === " ") {
              e.preventDefault();
              onPick(`/${c.name} `);
            }
          }}
        >
          <code style={slashCodeStyle}>
            /{c.name}
            {c.args ? ` ${c.args}` : ""}
          </code>
          <span style={{ opacity: 0.65 }}>{c.description}</span>
        </button>
      ))}
    </div>
  );
}

/**
 * Help card listing everything the chat can do — the same commands the model can
 * use as tools, which you can also invoke directly by typing them. Toggled by the
 * "?" button in either panel's header.
 */
export function CommandHelp({ commands, intro }: { commands: SlashCommandInfo[]; intro: string }) {
  return (
    <div style={helpCardStyle}>
      <div style={{ fontSize: 12, opacity: 0.8, marginBottom: 6 }}>{intro}</div>
      {commands.map((c) => (
        <div key={c.name} style={{ display: "flex", gap: 10, alignItems: "baseline", padding: "3px 0" }}>
          <code style={{ ...slashCodeStyle, minWidth: 132 }}>
            /{c.name}
            {c.args ? ` ${c.args}` : ""}
          </code>
          <span style={{ opacity: 0.7, fontSize: 12 }}>{c.description}</span>
        </div>
      ))}
    </div>
  );
}

const helpCardStyle = {
  borderTop: `1px solid ${t.border.faint}`,
  borderBottom: `1px solid ${t.border.faint}`,
  background: t.accent.wash,
  padding: "8px 12px",
  maxHeight: 260,
  overflowY: "auto",
} as const;

/** Tab-completion for a bare "/prefix" draft; undefined when nothing applies. */
export function completeSlash(draft: string, commands: SlashCommandInfo[]): string | undefined {
  if (!draft.startsWith("/") || /\s/.test(draft)) return undefined;
  const hit = commands.find((c) => c.name.startsWith(draft.slice(1).toLowerCase()));
  return hit ? `/${hit.name} ` : undefined;
}

const slashMenuStyle = {
  borderTop: `1px solid ${t.border.faint}`,
  maxHeight: 220,
  overflowY: "auto",
  display: "flex",
  flexDirection: "column",
} as const;

const slashHintStyle = {
  fontSize: 10,
  opacity: 0.5,
  padding: "6px 12px 2px",
} as const;

const slashItemStyle = {
  display: "flex",
  gap: 10,
  alignItems: "baseline",
  background: "transparent",
  color: "inherit",
  border: "none",
  textAlign: "left",
  padding: "5px 12px",
  fontSize: 12,
  cursor: "pointer",
} as const;

const slashCodeStyle = {
  color: ACCENT_BLUE,
  whiteSpace: "nowrap",
  fontSize: 12,
} as const;

/** Collapsible context-usage readout — a one-line summary that expands to the
 * donut + legend. Shared by both chat panels. */
export const UsageDisclosure = memo(function UsageDisclosure({ usage }: { usage: ContextUsage }) {
  const pct =
    usage.maxTokens !== undefined
      ? ` · ${Math.min(100, Math.round((usage.approxTokens / usage.maxTokens) * 100))}% of window`
      : "";
  const used = usage.approxTokens >= 1000 ? `${(usage.approxTokens / 1000).toFixed(1)}k` : usage.approxTokens;
  return (
    <details style={usageDetailsStyle}>
      <summary style={usageSummaryStyle}>
        Context: ~{used} tokens{pct} — see breakdown
      </summary>
      <div style={{ padding: "6px 10px 10px" }}>
        <ContextUsageDonut usage={usage} />
      </div>
    </details>
  );
});

const usageDetailsStyle = { borderBottom: `1px solid ${t.border.faint}` } as const;
const usageSummaryStyle = {
  cursor: "pointer",
  fontSize: 11,
  opacity: 0.7,
  padding: "6px 12px",
  listStyle: "revert",
} as const;

// Memoised: every keystroke in the draft (panel-local state) and every streamed
// token re-renders the panel — settled bubbles (which can hold images and link
// lists, and grow without bound over a session) must not re-render with it.
// Exported for the landing-page buddy panel, which renders the same bubbles.
// `onDelete(index)` must be a STABLE callback for the same reason — a per-bubble
// closure would defeat the memo.
export const MessageBubble = memo(function MessageBubble({
  message,
  index,
  onDelete,
  onOpenLocalFile,
  onAction,
  onSaveFile,
  onRunCode,
  onSaveProject,
  onBuildDocument,
  onDownloadData,
  fileActions,
  onUseImageAsReference,
  desktop,
  thinkingOpen,
  onThinkingOpenChange,
  streaming,
  justFinished,
}: {
  message: ChatMessageVM;
  index?: number;
  onDelete?: (index: number) => void;
  /** Open a local-file result (desktop `/find`). Stable callback (memo). */
  onOpenLocalFile?: (path: string) => void;
  /** Run a quick-reply action (sends its text). Stable callback (memo). */
  onAction?: (send: string) => void;
  /** Save a code block the assistant wrote as a file. Stable callback (memo). */
  onSaveFile?: (filename: string, content: string, mime: string) => Promise<string | true>;
  /** Run a code block (Python/JS/shell) on the host. Stable (memo). */
  onRunCode?: RunCodeFn;
  /** Zip + save the message's code blocks as one project (≥2 files). Stable (memo). */
  onSaveProject?: (files: ProjectFile[]) => Promise<string | true>;
  /** Generate + embed a designed document's images. Stable (memo). */
  onBuildDocument?: BuildDocumentFn;
  /** Download a grounded analysis-result table as .xlsx / .csv. Stable (memo). */
  onDownloadData?: (table: DataTable, name: string, format: "xlsx" | "csv") => void;
  /** Universal file-card actions (Download / Open in app / Open in library / Open on PC). Stable (memo). */
  fileActions?: FileActions;
  /** Adopt a searched picture as a reference for this chat's renders. Stable (memo). */
  onUseImageAsReference?: (item: { full: string; title?: string }) => void;
  /** Desktop build — enables the Open-on-PC action. */
  desktop?: boolean;
  /** This bubble is the LIVE one being streamed into — it gets a typing caret. On the bubble
   * rather than inside the markdown so it survives every re-render of the streamed content. */
  streaming?: boolean;
  /** This message is the reply that JUST landed, so the bubble condenses around it. Set by the
   * list, not inferred here: a bubble cannot know whether it replaced a stream or was loaded
   * from history, and replaying the animation on every old message when a chat opens would be
   * a wall of movement. */
  justFinished?: boolean;
  /** Whether this message's saved reasoning is expanded. The reader's ONE choice, shared with the
   * live block: it used to be hardcoded closed here, so the moment a turn finished its reasoning
   * collapsed under someone who had deliberately opened it. Defaults closed for older history. */
  thinkingOpen?: boolean;
  onThinkingOpenChange?: (open: boolean) => void;
}) {
  const isUser = message.role === "user";
  const url = useMessageImageUrl(message.image);
  const videoUrl = useMessageVideoUrl(message.video);
  // Assistant prose may contain fenced code blocks (a file the model created) —
  // render those as saveable cards; the user's own messages stay verbatim.
  const blocks = !isUser && message.text ? parseMessageBlocks(message.text) : undefined;
  // Per-block render kind: a saveable file card vs an inline snippet (illustrative code inside a doc) vs
  // prose. Stops a research doc full of examples from shattering into one "file" card per fence.
  const blockKinds = blocks ? classifyBlocks(blocks) : undefined;
  const fileCount = blockKinds?.reduce((n, k) => n + (k === "file" ? 1 : 0), 0) ?? 0;
  return (
    <div
      className={
        // While streaming there is no bubble at all — `forming` strips the pane so the letters
        // arrive straight onto the field. `solidify` runs once, on the message that replaces the
        // streaming one, which is a fresh mount and therefore plays its animation exactly once.
        `${cx.msg} ${cx.card} ${cx.msgFloat}` +
        (streaming ? ` ${cx.typing} ${cx.live} ${cx.forming}` : "") +
        (justFinished ? ` ${cx.solidify}` : "")
      }
      data-from={isUser ? "user" : "assistant"}
      // `background` is deliberately NOT set here. It used to be, and an inline background beats
      // the class that now paints the translucent floating pane — the same cascade trap that made
      // button hover invisible. .vr-msg-float owns the fill, the blur and the edge.
      style={{
        ...bubbleStyle,
        alignSelf: isUser ? "flex-end" : "flex-start",
      }}
    >
      {onDelete !== undefined && index !== undefined && (
        <button
          style={deleteButtonStyle}
          title="Delete this message (it leaves the conversation the model sees too)"
          aria-label="Delete message"
          onClick={() => onDelete(index)}
        >
          ✕
        </button>
      )}
      {!isUser && message.thinking ? (
        <ThinkingBlock
          text={message.thinking}
          open={thinkingOpen ?? false}
          label="💭 Reasoning"
          {...(onThinkingOpenChange ? { onOpenChange: onThinkingOpenChange } : {})}
        />
      ) : null}
      {blocks
        ? blocks.map((b, i) =>
            b.type === "code" ? (
              isDocBlock(b) && onBuildDocument ? (
                <DocumentCard
                  key={i}
                  code={b.code}
                  onBuildDocument={onBuildDocument}
                  {...(onSaveFile ? { onSaveFile } : {})}
                />
              ) : blockKinds?.[i] === "snippet" ? (
                // Illustrative code inside a document — read-only inline (copy), NOT a saveable file card.
                <InlineCode key={i} lang={b.lang} code={b.code} />
              ) : (
                <CodeCard
                  key={i}
                  lang={b.lang}
                  code={b.code}
                  {...(b.filename ? { filename: b.filename } : {})}
                  {...(onSaveFile ? { onSaveFile } : {})}
                  {...(onRunCode ? { onRunCode } : {})}
                  {...(fileActions ? { fileActions } : {})}
                  {...(desktop ? { desktop } : {})}
                />
              )
            ) : b.text.trim() ? (
              <div key={i} style={{ whiteSpace: "pre-wrap" }}>
                <Linkified text={b.text} />
              </div>
            ) : null,
          )
        : message.text
          ? (
            <div style={{ whiteSpace: "pre-wrap" }}>
              <Linkified text={message.text} />
            </div>
          )
          : null}
      {fileCount >= 2 && onSaveProject && blocks ? (
        <ProjectSaveBar
          files={projectFilesFromBlocks(blocks.filter((_, i) => blockKinds?.[i] === "file"))}
          onSaveProject={onSaveProject}
        />
      ) : null}
      {url ? (
        <ArrivingImage
          src={url}
          alt="Chat image"
          wrapStyle={{ marginTop: message.text ? 6 : 0 }}
          style={{
            display: "block",
            maxWidth: "100%",
            height: "auto", // keep the image's own aspect ratio (never stretched/cropped)
            maxHeight: 420,
            objectFit: "contain",
            borderRadius: 6,
          }}
        />
      ) : null}
      {videoUrl ? (
        message.video?.mimeType.startsWith("video/") ? (
          <video
            src={videoUrl}
            controls
            autoPlay
            loop
            muted
            playsInline
            style={{ display: "block", maxWidth: "100%", height: "auto", maxHeight: 420, borderRadius: 6, marginTop: message.text ? 6 : 0 }}
          />
        ) : (
          // An animated webp/gif loops natively in an <img> (no <video> controls needed).
          <ArrivingImage
            src={videoUrl}
            alt="Generated animation"
            wrapStyle={{ marginTop: message.text ? 6 : 0 }}
            style={{ display: "block", maxWidth: "100%", height: "auto", maxHeight: 420, objectFit: "contain", borderRadius: 6 }}
          />
        )
      ) : null}
      {message.analysis ? (
        <AnalysisBlock analysis={message.analysis} {...(onDownloadData ? { onDownloadData } : {})} />
      ) : null}
      {message.gallery?.length ? (
        <ImageGallery items={message.gallery} {...(onUseImageAsReference ? { onUseAsReference: onUseImageAsReference } : {})} />
      ) : null}
      {message.links?.length ? (
        <ol style={{ margin: "6px 0 0", paddingLeft: 18, fontSize: 11 }}>
          {message.links.map((l, i) => (
            <li key={i}>
              <a href={l.url} target="_blank" rel="noreferrer" style={{ color: ACCENT_BLUE }}>
                {l.title || l.url}
              </a>
            </li>
          ))}
        </ol>
      ) : null}
      {message.attachments?.length ? (
        <div style={{ display: "flex", flexDirection: "column", gap: 2, marginTop: 2 }}>
          {message.attachments.map((f, i) =>
            fileActions ? (
              <FileActionBar key={i} file={f} actions={fileActions} label {...(desktop ? { desktop } : {})} />
            ) : null,
          )}
        </div>
      ) : null}
      {message.files?.length ? (
        <div style={{ display: "flex", flexDirection: "column", gap: 4, marginTop: 6 }}>
          {message.files.map((f, i) =>
            // A found PC file: the universal card (Open in app / Download / Open on PC) when wired,
            // else the plain open-on-click chip the desktop /find has always shown.
            fileActions ? (
              <FileActionBar
                key={i}
                file={{ name: f.name, path: f.path, mime: "", kind: "found" }}
                actions={fileActions}
                label
                {...(desktop ? { desktop } : {})}
              />
            ) : (
              <button
                key={i}
                style={fileChipStyle}
                title={`Open ${f.path}`}
                onClick={() => onOpenLocalFile?.(f.path)}
              >
                📄 {f.name}
              </button>
            ),
          )}
        </div>
      ) : null}
      {message.actions?.length ? (
        <div style={{ display: "flex", gap: 6, marginTop: 6, flexWrap: "wrap" }}>
          {message.actions.map((a, i) => (
            <button key={i} style={fileChipStyle} onClick={() => onAction?.(a.send)}>
              {a.label}
            </button>
          ))}
        </div>
      ) : null}
    </div>
  );
});

const fileChipStyle = {
  display: "block",
  textAlign: "left",
  background: t.fill.subtle,
  color: "inherit",
  border: `1px solid ${t.border.button}`,
  borderRadius: 6,
  padding: "5px 8px",
  fontSize: 12,
  cursor: "pointer",
} as const;

const fileMenuStyle = {
  position: "absolute",
  zIndex: 5,
  marginTop: 4,
  display: "flex",
  flexDirection: "column",
  gap: 2,
  background: t.surface.sunken,
  border: `1px solid ${t.border.button}`,
  borderRadius: 6,
  padding: 4,
  minWidth: 150,
  boxShadow: "0 6px 18px rgba(0,0,0,0.4)",
} as const;

const fileMenuItemStyle = {
  textAlign: "left",
  background: "transparent",
  color: "inherit",
  border: "none",
  borderRadius: 4,
  padding: "5px 8px",
  fontSize: 12,
  cursor: "pointer",
  whiteSpace: "nowrap",
} as const;

type FileActionKey = "dl" | "app" | "lib" | "pc";
type FileActionItem = { key: FileActionKey; label: string; title: string; run: () => void | Promise<unknown> };

/** Which file-card actions apply to a file — pure so it's unit-testable. `has` flags which
 * callbacks the app wired. Rules: Download always (when wired); Open-in-app for everything but a
 * pure export; Open-in-library only for book-like files (not a bare image or export); Open-on-PC
 * desktop-only. Order is stable (download, app, library, pc) so the first stays the inline button. */
export function fileActionKeys(
  kind: FileRef["kind"],
  has: { download?: boolean; openInApp?: boolean; openInLibrary?: boolean; openOnPC?: boolean },
  desktop?: boolean,
): FileActionKey[] {
  const keys: FileActionKey[] = [];
  if (has.download) keys.push("dl");
  if (has.openInApp && kind !== "export") keys.push("app");
  if (has.openInLibrary && kind !== "image" && kind !== "export") keys.push("lib");
  if (desktop && has.openOnPC) keys.push("pc");
  return keys;
}

/**
 * Is this card a TEXT document — something the chat window can render as prose, whether or not it
 * currently holds the text? Extension counts as well as MIME, because a written `.md` reaches the
 * chat as a bare path with `mime: ""`, which is exactly the card that had no way to be read.
 */
export function isTextDocument(file: Pick<FileRef, "name" | "mime">): boolean {
  return (
    file.mime === "text/markdown" ||
    file.mime === "text/plain" ||
    /\.(md|markdown|txt|text)$/i.test(file.name)
  );
}

/**
 * The text a file card ALREADY carries, renderable inline ("📖 Read here"), or undefined when it
 * isn't a text document or the text has to be fetched. `content` when the card carries it, otherwise
 * decoded from its bytes — a text document is readable either way, and keying off `content` alone
 * meant a card that reached the reader carrying only bytes offered no way to read a .md at all, in a
 * chat window perfectly able to render it.
 */
export function inlineReadableText(file: Pick<FileRef, "name" | "mime" | "content" | "bytes">): string | undefined {
  if (!isTextDocument(file)) return undefined;
  if (file.content) return file.content;
  if (!file.bytes || file.bytes.byteLength === 0) return undefined;
  try {
    // `fatal` so undecodable bytes throw instead of coming back as a page of replacement characters,
    // which would render as a "document" made of garbage rather than simply offering no Read button.
    return new TextDecoder("utf-8", { fatal: true }).decode(new Uint8Array(file.bytes));
  } catch {
    return undefined;
  }
}

const FILE_ACTION_LABEL: Record<FileActionKey, { label: string; title: string }> = {
  dl: { label: "💾 Download", title: "Save a copy of this file" },
  app: { label: "📖 Open in app", title: "Open it in the reader (this also keeps it in your library)" },
  // "Open in library" claimed it opened the file and didn't — it only saved it. And since opening a
  // file ALSO adds it to the library, the two actions landed in the same place from the outside, which
  // is why they read as duplicates. The distinction that's actually useful is open-it versus just-keep-it.
  lib: { label: "📚 Add to library", title: "Keep it in your library without opening it now" },
  pc: { label: "🖥 Open on PC", title: "Open it in your computer's default app" },
};

/**
 * The universal file card's action bar — shown under ANY file the assistant created or found:
 * Download, Open in app, Open in library, Open on PC. Only the actions provided AND applicable to
 * the file/platform render; the first stays inline and the rest collapse into a ▾ More dropdown so
 * the row stays compact. One component, reused for code blocks, found files, and surfaced artifacts.
 */
export function FileActionBar({
  file,
  actions,
  desktop,
  label,
}: {
  file: FileRef;
  actions: FileActions;
  desktop?: boolean;
  /** Show the file name as a leading chip (used by the attachments list; off inside a CodeCard). */
  label?: boolean;
}) {
  const [busy, setBusy] = useState<string | undefined>();
  /** What the last action did, shown under the bar. Saving a document used to report NOTHING —
   * not where it went, not that it had happened, and not why it hadn't: the click set the chip to
   * "…" and then put it back, which from the outside is a button that does nothing whether it
   * worked or threw. Every other Save in the app says "✓ Saved to …"; this one is where the
   * assistant's own documents come out, so it's the one that most needed to. */
  const [note, setNote] = useState<{ ok: boolean; text: string } | undefined>();
  const [readOpen, setReadOpen] = useState(false);
  // The "⋯ More" menu is a native <details> — collapse it after a pick, or it stays open covering the
  // chat until the reader clicks the summary again (U5).
  const moreRef = useRef<HTMLDetailsElement>(null);
  const closeMore = (): void => {
    if (moreRef.current) moreRef.current.open = false;
  };
  // Reading a text document INLINE, without leaving the chat. The card's own text when it carries it;
  // otherwise fetched on the first click, because the most common way a `.md` reaches the chat is as a
  // bare path (the assistant wrote it, or a search found it) — which used to mean a Markdown file the
  // chat could render perfectly well had no button to render it, only "open it somewhere else".
  const ownText = useMemo(() => inlineReadableText(file), [file]);
  const [loadedText, setLoadedText] = useState<string | undefined>();
  const [readErr, setReadErr] = useState<string | undefined>();
  const [reading, setReading] = useState(false);
  const inlineText = ownText ?? loadedText;
  const canReadInline = ownText !== undefined || (isTextDocument(file) && !!actions.readText);
  const toggleRead = async (): Promise<void> => {
    if (readOpen) return setReadOpen(false);
    setReadOpen(true);
    if (inlineText !== undefined || !actions.readText) return;
    setReading(true);
    setReadErr(undefined);
    try {
      const text = await actions.readText(file);
      // `undefined` is "couldn't get it"; `""` is "got it, it's empty". Collapsing the two reported a
      // file that read perfectly well as unreachable — and the other way round, a blank panel would
      // have read as "this file is empty" when the file was simply out of reach.
      if (text === undefined) setReadErr(`Couldn't read “${file.name}” from here.`);
      else if (text.trim() === "") setReadErr(`“${file.name}” is empty.`);
      else setLoadedText(text);
    } catch (e) {
      setReadErr(`Couldn't read “${file.name}”: ${e instanceof Error ? e.message : String(e)}`);
    } finally {
      setReading(false);
    }
  };
  const runFor: Record<FileActionKey, () => void | Promise<unknown>> = {
    dl: async () => {
      const saved = await actions.download!(file);
      // undefined = the reader cancelled the name prompt. Nothing happened, so say nothing.
      if (saved === undefined) return;
      setNote({ ok: true, text: saved === true ? "✓ Saved (check your downloads)" : `✓ Saved to ${saved}` });
    },
    app: () => actions.openInApp!(file),
    lib: () => actions.openInLibrary!(file),
    pc: () => actions.openOnPC!(file),
  };
  const items: FileActionItem[] = fileActionKeys(
    file.kind,
    { download: !!actions.download, openInApp: !!actions.openInApp, openInLibrary: !!actions.openInLibrary, openOnPC: !!actions.openOnPC },
    desktop,
  ).map((key) => ({ key, ...FILE_ACTION_LABEL[key], run: runFor[key] }));
  if (items.length === 0) return null;
  const fire = async (it: FileActionItem) => {
    setBusy(it.key);
    setNote(undefined);
    try {
      await it.run();
    } catch (e) {
      // NOT swallowed. This used to be an empty catch trusting "the app surfaces its own error note",
      // which for a failed save it doesn't — so the one visible sign of a broken Save was the chip
      // going back to normal.
      setNote({ ok: false, text: `⚠ ${it.label} failed: ${e instanceof Error ? e.message : String(e)}` });
    } finally {
      setBusy(undefined);
    }
  };
  const primary = items[0]!;
  const rest = items.slice(1);
  return (
    <div>
    <div style={{ display: "flex", alignItems: "center", gap: 6, marginTop: 6, flexWrap: "wrap" }}>
      {label ? <span style={{ opacity: 0.7, fontSize: 11, marginRight: 2 }}>📎 {file.name}</span> : null}
      <button style={fileChipStyle} title={primary.title} disabled={busy === primary.key} onClick={() => void fire(primary)}>
        {busy === primary.key ? "…" : primary.label}
      </button>
      {canReadInline ? (
        <button
          style={readOpen ? { ...fileChipStyle, borderColor: t.accent.edge, color: t.accent.text } : fileChipStyle}
          title="Read this document right here in the chat (no need to open the reader)"
          disabled={reading}
          onClick={() => void toggleRead()}
        >
          {reading ? "…" : readOpen ? "▾ Hide" : "📖 Read here"}
        </button>
      ) : null}
      {rest.length >= 1 || actions.openAs ? (
        <details ref={moreRef} style={{ position: "relative" }}>
          <summary style={{ ...fileChipStyle, listStyle: "none", cursor: "pointer" }}>⋯ More</summary>
          <div style={fileMenuStyle}>
            {rest.map((it) => (
              <button
                key={it.key}
                style={fileMenuItemStyle}
                title={it.title}
                disabled={busy === it.key}
                onClick={() => {
                  closeMore();
                  void fire(it);
                }}
              >
                {it.label}
              </button>
            ))}
            {actions.openAs ? (
              <>
                <div style={{ opacity: 0.5, fontSize: 10, padding: "4px 8px 2px" }}>Open as…</div>
                {OPEN_AS_CHOICES.map((c) => (
                  <button
                    key={c.as}
                    style={fileMenuItemStyle}
                    onClick={() => {
                      closeMore();
                      actions.openAs!(file, c.as);
                    }}
                  >
                    {c.label}
                  </button>
                ))}
              </>
            ) : null}
          </div>
        </details>
      ) : null}
    </div>
    {note ? (
      <div style={{ fontSize: 11, marginTop: 4, opacity: note.ok ? 0.7 : 1, color: note.ok ? undefined : DANGER_RED }}>
        {note.text}
      </div>
    ) : null}
    {readOpen && readErr ? (
      <div style={{ fontSize: 11, marginTop: 4, color: DANGER_RED }}>⚠ {readErr}</div>
    ) : null}
    {readOpen && inlineText !== undefined ? (
      <div
        style={{
          maxHeight: 440,
          overflowY: "auto",
          marginTop: 8,
          padding: "12px 16px",
          border: `1px solid ${t.border.subtle}`,
          borderRadius: 8,
          background: t.fill.subtle,
        }}
      >
        <DocBlocksView markdown={inlineText} />
      </div>
    ) : null}
    </div>
  );
}

/**
 * A row of retrieved-image thumbnails (a multi-hit `search_images`). Every result
 * shows at once — so "show me 3 images of X" actually shows several — and clicking
 * a thumbnail enlarges it in place (no new tab, which the desktop webview blocks).
 */
function ImageGallery({
  items,
  onUseAsReference,
}: {
  items: { thumb: string; full: string; title?: string }[];
  /** Adopt THIS picture as a reference for the chat's renders. Absent ⇒ no button (nothing to run
   * it), which is the honest state on a host that can't download from arbitrary image hosts. */
  onUseAsReference?: (item: { full: string; title?: string }) => void;
}) {
  const [enlarged, setEnlarged] = useState<number | null>(null);
  const open = enlarged != null ? items[enlarged] : undefined;
  // Escape closes the enlarged view (the lightbox has no close chrome of its own).
  useEffect(() => {
    if (enlarged == null) return;
    const onKey = (e: KeyboardEvent): void => {
      if (e.key === "Escape") setEnlarged(null);
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [enlarged]);
  return (
    <div style={{ marginTop: 6 }}>
      <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
        {items.map((g, i) => (
          <img
            key={i}
            src={g.thumb}
            alt={g.title || "image result"}
            title={g.title || ""}
            loading="lazy"
            decoding="async"
            // Real button semantics for the click-to-enlarge behavior (an <img> is
            // otherwise unreachable by keyboard).
            role="button"
            tabIndex={0}
            aria-label={`${enlarged === i ? "Shrink" : "Enlarge"} ${g.title || "image result"}`}
            onClick={() => setEnlarged(enlarged === i ? null : i)}
            onKeyDown={(e) => {
              if (e.key === "Enter" || e.key === " ") {
                e.preventDefault();
                setEnlarged(enlarged === i ? null : i);
              }
            }}
            style={{
              width: 116,
              height: 116,
              objectFit: "cover",
              borderRadius: 6,
              cursor: enlarged === i ? "zoom-out" : "zoom-in",
              border:
                enlarged === i ? `2px solid ${ACCENT_BLUE}` : `1px solid ${t.fill.strong}`,
            }}
          />
        ))}
      </div>
      {/* Adopting is offered on the ENLARGED picture, not on every thumbnail: it is a deliberate act
          about one specific result, and a row of buttons under a twelve-hit grid invites the misclick
          this whole path is meant to avoid. */}
      {open && onUseAsReference ? (
        <button
          style={{
            marginTop: 6,
            fontSize: 12,
            padding: "4px 10px",
            borderRadius: 6,
            border: `1px solid ${t.border.button}`,
            background: t.fill.base,
            color: "inherit",
            cursor: "pointer",
          }}
          onClick={() => onUseAsReference({ full: open.full, ...(open.title ? { title: open.title } : {}) })}
          title="Draw from this picture — it becomes a reference for images made in this chat"
        >
          🖼 Use as reference
        </button>
      ) : null}
      {open ? (
        <img
          src={open.full}
          alt={open.title || "enlarged image"}
          decoding="async"
          role="button"
          tabIndex={0}
          aria-label="Close enlarged image"
          onClick={() => setEnlarged(null)}
          onKeyDown={(e) => {
            if (e.key === "Enter" || e.key === " ") {
              e.preventDefault();
              setEnlarged(null);
            }
          }}
          style={{
            display: "block",
            maxWidth: "100%",
            height: "auto",
            maxHeight: 420,
            objectFit: "contain",
            borderRadius: 6,
            marginTop: 6,
            cursor: "zoom-out",
          }}
        />
      ) : null}
    </div>
  );
}

/**
 * A thinking model's live reasoning, shown dimmed and auto-scrolling while it works
 * (so a long reason-before-answering reads as visible progress, not a frozen hang).
 * Collapsible — the reasoning isn't the answer, so it stays out of the way.
 *
 * The SAME choice governs the live block and the finished message's saved reasoning — those are one
 * disclosure as far as the reader is concerned, and having the saved one hardcoded shut meant it
 * collapsed the instant a turn ended, under someone who had just opened it. Only the newest reply
 * follows the preference; older history stays collapsed, or scrolling back would be a wall of it.
 *
 * `onOpenChange` reports the reader opening or closing it, so the HOST can remember that choice and
 * feed it back as `open` next time. Without that the block is re-created on every reply and springs
 * back to its default, re-opening something the reader just closed (and vice versa) — the collapse
 * only ever lasted until the next message.
 */
export function ThinkingBlock({
  text,
  open = true,
  label = "💭 Thinking…",
  onOpenChange,
  live,
}: {
  text: string;
  open?: boolean;
  label?: string;
  onOpenChange?: (open: boolean) => void;
  /** This reasoning is arriving RIGHT NOW. Saved reasoning on a finished message is not live and
   * must not shimmer or glow — an old conversation lighting up says the model is still working. */
  live?: boolean;
}) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const el = ref.current;
    if (el && open) el.scrollTop = el.scrollHeight;
  }, [text, open]);
  return (
    <details
      open={open}
      onToggle={(e) => {
        const next = (e.currentTarget as HTMLDetailsElement).open;
        if (next !== open) onOpenChange?.(next);
      }}
      className={live ? cx.live : undefined}
      style={thinkingStyle}
    >
      <summary
        className={live ? cx.thinking : undefined}
        style={{ cursor: "pointer", fontSize: 11, opacity: live ? 1 : 0.7 }}
      >
        {label}
      </summary>
      <div
        ref={ref}
        style={{
          whiteSpace: "pre-wrap",
          fontSize: 12,
          opacity: 0.6,
          fontStyle: "italic",
          marginTop: 4,
          maxHeight: 160,
          overflowY: "auto",
        }}
      >
        {text}
      </div>
    </details>
  );
}

const thinkingStyle = {
  alignSelf: "flex-start",
  maxWidth: "92%",
  border: `1px dashed ${t.border.button}`,
  borderRadius: 8,
  padding: "6px 10px",
  background: t.fill.subtle,
} as const;

/**
 * A grounded analyze_data result: the computed table (these numbers are exact — the
 * app calculated them over the real cells), plus an optional chart of the result.
 */
function AnalysisBlock({
  analysis,
  onDownloadData,
}: {
  analysis: { table: DataTable; summary?: string; chart?: AnalyzeChart };
  onDownloadData?: (table: DataTable, name: string, format: "xlsx" | "csv") => void;
}) {
  const { table, chart } = analysis;
  return (
    <div style={{ marginTop: 6 }}>
      <DataTablePreview table={table} maxRows={50} maxHeight={320} />
      {chart ? <AnalysisChart table={table} chart={chart} /> : null}
      {onDownloadData ? (
        <div style={{ display: "flex", gap: 6, marginTop: 6 }}>
          <button style={dataDownloadBtn} title="Download this result as a real Excel workbook" onClick={() => onDownloadData(table, "analysis", "xlsx")}>
            ⬇ Excel
          </button>
          <button style={dataDownloadBtn} title="Download this result as CSV" onClick={() => onDownloadData(table, "analysis", "csv")}>
            ⬇ CSV
          </button>
        </div>
      ) : null}
    </div>
  );
}

const dataDownloadBtn: React.CSSProperties = {
  background: t.state.good,
  border: `1px solid ${t.state.good}`,
  color: "inherit",
  borderRadius: 6,
  padding: "2px 8px",
  fontSize: 11,
  cursor: "pointer",
};

/** Render an analysis result table as a chart by taking its first text + numeric columns. */
function AnalysisChart({ table, chart }: { table: DataTable; chart: AnalyzeChart }) {
  // DataChart supports bar/line/scatter; a requested "pie" falls back to bar.
  const dataset = chartDatasetFromTable(table, chart === "line" ? "line" : "bar", 40);
  if (!dataset) return null;
  return (
    <div style={{ marginTop: 4 }}>
      <DataChart dataset={dataset} />
    </div>
  );
}

/** Inline prose with clickable bare URLs. */
function Linkified({ text }: { text: string }) {
  return (
    <>
      {linkifyText(text).map((seg, i) =>
        "url" in seg ? (
          <a key={i} href={seg.url} target="_blank" rel="noreferrer" style={{ color: ACCENT_BLUE }}>
            {seg.label ?? seg.url}
          </a>
        ) : (
          <span key={i}>{seg.text}</span>
        ),
      )}
    </>
  );
}

/**
 * A code/content block the assistant wrote (a webpage, a CSV worksheet, a
 * script…), with Save (to disk / download), Copy, and — for HTML — Preview.
 * The model "creates" the file; the user saves it with a click (a real gesture,
 * so browser downloads aren't blocked).
 */
/** An illustrative code snippet inside a document — read-only, with a Copy button but NO save/file
 * actions (it isn't a file the model created, just an example). Keeps a research doc from fragmenting
 * into many saveable "file" cards. */
function InlineCode({ lang, code }: { lang: string; code: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <div style={{ position: "relative", margin: "6px 0" }}>
      <div style={{ ...codeHeaderStyle, opacity: 0.7 }}>
        <span>{lang || "code"}</span>
        <button
          style={codeBtnStyle}
          onClick={() => {
            void navigator.clipboard?.writeText(code);
            setCopied(true);
            setTimeout(() => setCopied(false), 1200);
          }}
        >
          {copied ? "Copied" : "📋 Copy"}
        </button>
      </div>
      <pre style={codePreStyle}>
        <code>{code}</code>
      </pre>
    </div>
  );
}

function CodeCard({
  lang,
  code,
  filename: rawFilename,
  onSaveFile,
  onRunCode,
  fileActions,
  desktop,
}: {
  lang: string;
  code: string;
  filename?: string;
  onSaveFile?: (filename: string, content: string, mime: string) => Promise<string | true>;
  onRunCode?: RunCodeFn;
  /** Universal file-card actions (open in app / library / on PC) for the file this block creates. */
  fileActions?: FileActions;
  desktop?: boolean;
}) {
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState<string | undefined>();
  const [previewOpen, setPreviewOpen] = useState(false);
  const [running, setRunning] = useState(false);
  const [output, setOutput] = useState<RunCodeResult | undefined>();
  // Object URLs handed to new tabs, revoked on unmount as well as by the grace timer —
  // a card unmounted before the timer fires must not leak its blob.
  const tabUrls = useRef<Set<string>>(new Set());
  useEffect(() => {
    const urls = tabUrls.current;
    return () => {
      for (const u of urls) URL.revokeObjectURL(u);
    };
  }, []);
  const { filename, saveName, mime } = resolveCodeFile(lang, rawFilename);
  const ext = (filename.split(".").pop() ?? "").toLowerCase();
  const previewable = ext === "html" || ext === "svg";
  const l = (lang || "").toLowerCase();
  const runnable = !!onRunCode && (["py", "js", "sh"].includes(ext) || ["python", "js", "javascript", "node", "sh", "bash", "shell"].includes(l));
  const save = async () => {
    if (!onSaveFile) return;
    try {
      const r = await onSaveFile(saveName, code, mime);
      setSaved(typeof r === "string" ? r : "saved");
    } catch (e) {
      // Surface a failed save where the "saved to …" note would go — not an unhandled rejection.
      setSaved(`save failed: ${e instanceof Error ? e.message : String(e)}`);
    }
  };
  const run = async () => {
    if (!onRunCode) return;
    setRunning(true);
    setOutput(undefined);
    try {
      setOutput(await onRunCode(lang, code, rawFilename));
    } catch (e) {
      setOutput({ error: e instanceof Error ? e.message : String(e) });
    } finally {
      setRunning(false);
    }
  };
  // Open the rendered page in a new tab (a real click → not blocked). The 30s grace
  // period gives the tab time to load before the blob URL is revoked.
  const openInTab = () => {
    const url = URL.createObjectURL(new Blob([code], { type: mime }));
    tabUrls.current.add(url);
    window.open(url, "_blank", "noreferrer");
    setTimeout(() => {
      tabUrls.current.delete(url);
      URL.revokeObjectURL(url);
    }, 30_000);
  };
  return (
    <div style={codeCardStyle}>
      <div style={codeHeaderStyle}>
        <span style={{ opacity: 0.7 }} title={filename}>{lang || "text"} · {filename}</span>
        <span style={{ display: "flex", gap: 6 }}>
          {onSaveFile && (
            <button style={codeBtnStyle} onClick={() => void save()}>
              💾 Save
            </button>
          )}
          {runnable && (
            <button style={codeBtnStyle} onClick={() => void run()} disabled={running} title="Run this code on the desktop and show its output here">
              {running ? "Running…" : "▶ Run"}
            </button>
          )}
          {previewable && (
            <button style={codeBtnStyle} onClick={() => setPreviewOpen((o) => !o)} title="Render it right here in the chat">
              {previewOpen ? "▾ Hide preview" : "▶ Preview"}
            </button>
          )}
          {previewable && (
            <button
              style={codeBtnStyle}
              onClick={openInTab}
              title="Open the rendered page in a new browser tab"
              aria-label="Open the rendered page in a new browser tab"
            >
              ↗ Tab
            </button>
          )}
          <button
            style={codeBtnStyle}
            onClick={() => {
              void navigator.clipboard?.writeText(code);
              setCopied(true);
              setTimeout(() => setCopied(false), 1200);
            }}
          >
            {copied ? "Copied" : "📋 Copy"}
          </button>
        </span>
      </div>
      {fileActions ? (
        // The created file's universal actions (Save above is the Download; these add the rest).
        <FileActionBar
          file={{ name: filename, mime, kind: runnable || /^(ts|tsx|js|jsx|py|rb|go|rs|java|c|cpp|sh|css|json)$/.test(ext) ? "code" : "text", content: code }}
          actions={{
            ...(fileActions.openInApp ? { openInApp: fileActions.openInApp } : {}),
            ...(fileActions.openInLibrary ? { openInLibrary: fileActions.openInLibrary } : {}),
            ...(fileActions.openOnPC ? { openOnPC: fileActions.openOnPC } : {}),
          }}
          {...(desktop ? { desktop } : {})}
        />
      ) : null}
      {previewOpen && previewable ? (
        // Sandboxed in-app render: scripts run (so a coded page/widget actually works) but it has no
        // same-origin access — it can't touch the app, cookies, or storage.
        <iframe
          title={`Preview of ${filename}`}
          srcDoc={code}
          sandbox="allow-scripts allow-forms allow-popups allow-modals"
          style={{ width: `100%`, height: 320, border: `1px solid ${t.fill.strong}`, borderRadius: 6, background: `#fff` }}
        />
      ) : (
        <pre style={codePreStyle}>
          <code>{code}</code>
        </pre>
      )}
      {output && (
        <pre style={{ ...codePreStyle, borderTop: `1px solid ${t.border.subtle}`, opacity: 0.95 }}>
          <code>
            {output.error
              ? `⚠ ${output.error}`
              : `[exit ${output.code ?? "?"}${output.cwd ? ` · in ${output.cwd}` : ""}]` +
                (output.stdout ? `\n${output.stdout.slice(0, 6000)}` : "") +
                (output.stderr ? `\n⚠ ${output.stderr.slice(0, 3000)}` : "") +
                (!output.stdout && !output.stderr ? "\n(no output)" : "")}
          </code>
        </pre>
      )}
      {saved && (
        <div style={{ fontSize: 11, opacity: 0.7, padding: "4px 8px" }}>
          {saved === "saved" ? "✓ Saved (check your downloads)" : `✓ Saved to ${saved}`}
        </div>
      )}
    </div>
  );
}

/** "Save all as project (.zip)" — appears under a message with ≥2 code blocks, so a
 * linked multi-file answer is kept together (with its relative paths) in one archive. */
function ProjectSaveBar({
  files,
  onSaveProject,
}: {
  files: ProjectFile[];
  onSaveProject: (files: ProjectFile[]) => Promise<string | true>;
}) {
  const [saved, setSaved] = useState<string | undefined>();
  const [busy, setBusy] = useState(false);
  const save = async () => {
    setBusy(true);
    try {
      const r = await onSaveProject(files);
      setSaved(typeof r === "string" ? r : "saved");
    } finally {
      setBusy(false);
    }
  };
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 6, flexWrap: "wrap" }}>
      <button style={codeBtnStyle} onClick={() => void save()} disabled={busy} title={files.map((f) => f.name).join(", ")}>
        📦 {busy ? "Zipping…" : `Save all ${files.length} files as project (.zip)`}
      </button>
      {saved ? (
        <span style={{ fontSize: 11, opacity: 0.7 }}>
          {saved === "saved" ? "✓ Saved (check your downloads)" : `✓ Saved to ${saved}`}
        </span>
      ) : null}
    </div>
  );
}

/** A designed HTML document whose images the app generates and embeds. Shows the
 * source, a "Generate N images & build" action, progress, then Preview + Save of the
 * finished self-contained document. */
function DocumentCard({
  code,
  onBuildDocument,
  onSaveFile,
}: {
  code: string;
  onBuildDocument: BuildDocumentFn;
  onSaveFile?: (filename: string, content: string, mime: string) => Promise<string | true>;
}) {
  const imageCount = parseDocImages(code).length;
  const [building, setBuilding] = useState(false);
  const [progress, setProgress] = useState<{ done: number; total: number }>();
  const [built, setBuilt] = useState<{ html: string; generated: number; failed: number }>();
  const [saved, setSaved] = useState<string | undefined>();
  const [error, setError] = useState("");
  // Object URLs handed to preview tabs, revoked on unmount as well as by the grace
  // timer — a card unmounted before the timer fires must not leak its blob.
  const tabUrls = useRef<Set<string>>(new Set());
  useEffect(() => {
    const urls = tabUrls.current;
    return () => {
      for (const u of urls) URL.revokeObjectURL(u);
    };
  }, []);

  const html = built?.html ?? code;
  const build = async () => {
    setBuilding(true);
    setError("");
    setProgress({ done: 0, total: imageCount });
    try {
      const r = await onBuildDocument(code, (done, total) => setProgress({ done, total }));
      setBuilt(r);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBuilding(false);
      setProgress(undefined);
    }
  };
  const preview = () => {
    const url = URL.createObjectURL(new Blob([html], { type: "text/html" }));
    tabUrls.current.add(url);
    window.open(url, "_blank", "noreferrer");
    setTimeout(() => {
      tabUrls.current.delete(url);
      URL.revokeObjectURL(url);
    }, 30_000);
  };
  const save = async () => {
    if (!onSaveFile) return;
    const r = await onSaveFile("document.html", html, "text/html");
    setSaved(typeof r === "string" ? r : "saved");
  };

  return (
    <div style={codeCardStyle}>
      <div style={codeHeaderStyle}>
        <span style={{ opacity: 0.7 }}>
          🎨 designed document · {imageCount} image{imageCount === 1 ? "" : "s"}
          {built ? ` · ${built.generated} generated${built.failed ? `, ${built.failed} failed` : ""}` : ""}
        </span>
        <span style={{ display: "flex", gap: 6 }}>
          {!built && (
            <button style={codeBtnStyle} onClick={() => void build()} disabled={building}>
              {building
                ? `🎨 Generating ${progress ? `${progress.done}/${progress.total}` : ""}…`
                : `🎨 Generate ${imageCount} image${imageCount === 1 ? "" : "s"} & build`}
            </button>
          )}
          <button style={codeBtnStyle} onClick={preview} disabled={building}>
            ▶ Preview
          </button>
          {onSaveFile && built && (
            <button style={codeBtnStyle} onClick={() => void save()}>
              💾 Save
            </button>
          )}
        </span>
      </div>
      <pre style={codePreStyle}>
        <code>{built ? "<!-- images embedded — Preview or Save the finished document -->" : code}</code>
      </pre>
      {error ? <div style={{ fontSize: 11, color: DANGER_RED, padding: "4px 8px" }}>{error}</div> : null}
      {saved && (
        <div style={{ fontSize: 11, opacity: 0.7, padding: "4px 8px" }}>
          {saved === "saved" ? "✓ Saved (check your downloads)" : `✓ Saved to ${saved}`}
        </div>
      )}
    </div>
  );
}

const codeCardStyle = {
  border: `1px solid ${t.border.input}`,
  borderRadius: 8,
  margin: "6px 0",
  overflow: "hidden",
  background: "rgba(0,0,0,0.25)",
} as const;
const codeHeaderStyle = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  gap: 8,
  padding: "4px 8px",
  fontSize: 11,
  borderBottom: `1px solid ${t.border.faint}`,
} as const;
const codeBtnStyle = {
  background: t.fill.base,
  color: "inherit",
  border: `1px solid ${t.border.button}`,
  borderRadius: 5,
  padding: "2px 6px",
  fontSize: 11,
  cursor: "pointer",
} as const;
const codePreStyle = {
  margin: 0,
  padding: 8,
  maxHeight: 280,
  overflow: "auto",
  fontSize: 12,
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
  whiteSpace: "pre",
} as const;

/** Object URL for a bytes image (revoked on change); pass-through for hotlinks. */
function useMessageImageUrl(image: ChatMessageVM["image"]): string | undefined {
  const bytes = image && "bytes" in image ? image : undefined;
  const [url, setUrl] = useState<string | undefined>(undefined);
  useEffect(() => {
    if (!bytes) {
      setUrl(undefined);
      return;
    }
    const objectUrl = URL.createObjectURL(new Blob([bytes.bytes], { type: bytes.mimeType }));
    setUrl(objectUrl);
    return () => URL.revokeObjectURL(objectUrl);
  }, [bytes]);
  if (image && "sourceUrl" in image) return image.sourceUrl;
  return url;
}

/** Object URL for an inline video clip's bytes (revoked on unmount / change). */
function useMessageVideoUrl(video: ChatMessageVM["video"]): string | undefined {
  const [url, setUrl] = useState<string | undefined>(undefined);
  // Latest clip, read inside the effect — so the effect can rebuild the URL without depending on the
  // `video` object's IDENTITY (see `key` below).
  const videoRef = useRef(video);
  videoRef.current = video;
  // Key the blob URL on the clip's CONTENT (mime + byte size), NOT the object reference. On a linked
  // phone the desktop mirror re-pushes the chat ~8×/sec, rebuilding the message (and its `video`) object
  // each time; keying on identity would revoke + recreate the blob URL under the <video> element on every
  // push, and a URL revoked mid-load leaves the clip blank until a remount (the "only loads after
  // switching away and back" bug). A stable content key creates the URL once and leaves it alone.
  const key = video ? `${video.mimeType}:${video.bytes.byteLength}` : "";
  useEffect(() => {
    const v = videoRef.current;
    if (!v) {
      setUrl(undefined);
      return;
    }
    const objectUrl = URL.createObjectURL(new Blob([v.bytes], { type: v.mimeType }));
    setUrl(objectUrl);
    return () => URL.revokeObjectURL(objectUrl);
  }, [key]);
  return url;
}

const overlayStyle = {
  position: "fixed",
  inset: 0,
  background: "rgba(0,0,0,0.5)",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  zIndex: 60,
} as const;

const panelStyle = {
  width: "min(680px, 94vw)",
  height: "min(78vh, 720px)",
  background: t.surface.card,
  color: t.text.base,
  border: `1px solid ${t.border.subtle}`,
  borderRadius: 10,
  display: "flex",
  flexDirection: "column",
  overflow: "hidden",
} as const;

const bubbleStyle = {
  maxWidth: "85%",
  padding: "8px 10px",
  borderRadius: 8,
  fontSize: 13,
  lineHeight: 1.45,
  position: "relative",
} as const;

const deleteButtonStyle = {
  position: "absolute",
  top: 2,
  right: 2,
  background: "transparent",
  color: "inherit",
  border: "none",
  fontSize: 10,
  opacity: 0.35,
  cursor: "pointer",
  padding: "2px 4px",
} as const;
